// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "stitchNeighbors.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic stitchNeighbors::ap_const_logic_1 = sc_dt::Log_1;
const bool stitchNeighbors::ap_const_boolean_1 = true;
const sc_lv<32> stitchNeighbors::ap_const_lv32_14 = "10100";
const sc_lv<32> stitchNeighbors::ap_const_lv32_16 = "10110";
const sc_lv<3> stitchNeighbors::ap_const_lv3_4 = "100";
const sc_lv<3> stitchNeighbors::ap_const_lv3_0 = "000";
const sc_lv<32> stitchNeighbors::ap_const_lv32_17 = "10111";
const sc_lv<32> stitchNeighbors::ap_const_lv32_19 = "11001";
const sc_lv<32> stitchNeighbors::ap_const_lv32_A = "1010";
const sc_lv<10> stitchNeighbors::ap_const_lv10_3FF = "1111111111";
const sc_lv<32> stitchNeighbors::ap_const_lv32_13 = "10011";
const sc_lv<32> stitchNeighbors::ap_const_lv32_1F = "11111";
const sc_lv<32> stitchNeighbors::ap_const_lv32_1A = "11010";
const sc_lv<10> stitchNeighbors::ap_const_lv10_0 = "0000000000";
const sc_lv<32> stitchNeighbors::ap_const_lv32_400000 = "10000000000000000000000";
const sc_lv<1> stitchNeighbors::ap_const_lv1_1 = "1";
const sc_logic stitchNeighbors::ap_const_logic_0 = sc_dt::Log_0;

stitchNeighbors::stitchNeighbors(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_and_ln879_1_fu_360_p2);
    sensitive << ( and_ln879_fu_354_p2 );
    sensitive << ( icmp_ln879_fu_82_p2 );

    SC_METHOD(thread_and_ln879_fu_354_p2);
    sensitive << ( icmp_ln879_1_fu_98_p2 );
    sensitive << ( phiStitch_fu_124_p2 );

    SC_METHOD(thread_and_ln895_1_fu_386_p2);
    sensitive << ( and_ln879_1_fu_360_p2 );
    sensitive << ( xor_ln895_fu_380_p2 );

    SC_METHOD(thread_and_ln895_fu_366_p2);
    sensitive << ( and_ln879_1_fu_360_p2 );
    sensitive << ( icmp_ln895_fu_174_p2 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( select_ln895_1_fu_392_p3 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( select_ln895_3_fu_408_p3 );

    SC_METHOD(thread_icmp_ln879_1_fu_98_p2);
    sensitive << ( trunc_ln1503_1_fu_88_p4 );

    SC_METHOD(thread_icmp_ln879_fu_82_p2);
    sensitive << ( trunc_ln_fu_72_p4 );

    SC_METHOD(thread_icmp_ln895_fu_174_p2);
    sensitive << ( trunc_ln214_fu_130_p1 );
    sensitive << ( trunc_ln214_1_fu_134_p1 );

    SC_METHOD(thread_lhs_V_1_fu_190_p1);
    sensitive << ( trunc_ln1503_4_fu_180_p4 );

    SC_METHOD(thread_lhs_V_2_fu_284_p1);
    sensitive << ( trunc_ln1503_5_fu_222_p4 );

    SC_METHOD(thread_lhs_V_fu_138_p1);
    sensitive << ( trunc_ln214_fu_130_p1 );

    SC_METHOD(thread_pegged_cEtSum_V_1_fu_166_p3);
    sensitive << ( tmp_2_fu_152_p3 );
    sensitive << ( pegged_cEtSum_V_fu_160_p2 );

    SC_METHOD(thread_pegged_cEtSum_V_fu_160_p2);
    sensitive << ( trunc_ln214_fu_130_p1 );
    sensitive << ( trunc_ln214_1_fu_134_p1 );

    SC_METHOD(thread_pegged_tEtSum_V_1_fu_214_p3);
    sensitive << ( tmp_3_fu_200_p3 );
    sensitive << ( pegged_tEtSum_V_fu_208_p2 );

    SC_METHOD(thread_pegged_tEtSum_V_2_fu_302_p2);
    sensitive << ( trunc_ln214_fu_130_p1 );
    sensitive << ( trunc_ln1503_5_fu_222_p4 );

    SC_METHOD(thread_pegged_tEtSum_V_3_fu_308_p3);
    sensitive << ( tmp_4_fu_294_p3 );
    sensitive << ( pegged_tEtSum_V_2_fu_302_p2 );

    SC_METHOD(thread_pegged_tEtSum_V_fu_208_p2);
    sensitive << ( trunc_ln214_1_fu_134_p1 );
    sensitive << ( trunc_ln1503_4_fu_180_p4 );

    SC_METHOD(thread_phiStitch_fu_124_p2);
    sensitive << ( trunc_ln1503_2_fu_104_p4 );
    sensitive << ( trunc_ln1503_3_fu_114_p4 );

    SC_METHOD(thread_ret_V_1_fu_194_p2);
    sensitive << ( rhs_V_fu_142_p1 );
    sensitive << ( lhs_V_1_fu_190_p1 );

    SC_METHOD(thread_ret_V_2_fu_248_p5);
    sensitive << ( tmp_fu_238_p4 );
    sensitive << ( pegged_tEtSum_V_1_fu_214_p3 );
    sensitive << ( pegged_cEtSum_V_1_fu_166_p3 );

    SC_METHOD(thread_ret_V_3_fu_270_p6);
    sensitive << ( trunc_ln1503_2_fu_104_p4 );
    sensitive << ( tmp_1_fu_260_p4 );
    sensitive << ( tEt_leftOver_V_fu_232_p2 );

    SC_METHOD(thread_ret_V_4_fu_288_p2);
    sensitive << ( lhs_V_fu_138_p1 );
    sensitive << ( lhs_V_2_fu_284_p1 );

    SC_METHOD(thread_ret_V_5_fu_334_p2);
    sensitive << ( tmp4_fu_322_p5 );

    SC_METHOD(thread_ret_V_6_fu_340_p6);
    sensitive << ( trunc_ln1503_2_fu_104_p4 );
    sensitive << ( pegged_cEtSum_V_1_fu_166_p3 );
    sensitive << ( tmp_1_fu_260_p4 );
    sensitive << ( pegged_tEtSum_V_3_fu_308_p3 );

    SC_METHOD(thread_ret_V_fu_146_p2);
    sensitive << ( rhs_V_fu_142_p1 );
    sensitive << ( lhs_V_fu_138_p1 );

    SC_METHOD(thread_rhs_V_fu_142_p1);
    sensitive << ( trunc_ln214_1_fu_134_p1 );

    SC_METHOD(thread_select_ln895_1_fu_392_p3);
    sensitive << ( and_ln895_1_fu_386_p2 );
    sensitive << ( ret_V_5_fu_334_p2 );
    sensitive << ( select_ln895_fu_372_p3 );

    SC_METHOD(thread_select_ln895_2_fu_400_p3);
    sensitive << ( Bi_data_V );
    sensitive << ( and_ln895_fu_366_p2 );
    sensitive << ( ret_V_3_fu_270_p6 );

    SC_METHOD(thread_select_ln895_3_fu_408_p3);
    sensitive << ( and_ln895_1_fu_386_p2 );
    sensitive << ( ret_V_6_fu_340_p6 );
    sensitive << ( select_ln895_2_fu_400_p3 );

    SC_METHOD(thread_select_ln895_fu_372_p3);
    sensitive << ( Ai_data_V );
    sensitive << ( and_ln895_fu_366_p2 );
    sensitive << ( ret_V_2_fu_248_p5 );

    SC_METHOD(thread_tEt_leftOver_V_1_fu_316_p2);
    sensitive << ( trunc_ln214_fu_130_p1 );
    sensitive << ( trunc_ln1503_4_fu_180_p4 );

    SC_METHOD(thread_tEt_leftOver_V_fu_232_p2);
    sensitive << ( trunc_ln214_1_fu_134_p1 );
    sensitive << ( trunc_ln1503_5_fu_222_p4 );

    SC_METHOD(thread_tmp4_fu_322_p5);
    sensitive << ( tmp_fu_238_p4 );
    sensitive << ( tEt_leftOver_V_1_fu_316_p2 );

    SC_METHOD(thread_tmp_1_fu_260_p4);
    sensitive << ( Bi_data_V );

    SC_METHOD(thread_tmp_2_fu_152_p3);
    sensitive << ( ret_V_fu_146_p2 );

    SC_METHOD(thread_tmp_3_fu_200_p3);
    sensitive << ( ret_V_1_fu_194_p2 );

    SC_METHOD(thread_tmp_4_fu_294_p3);
    sensitive << ( ret_V_4_fu_288_p2 );

    SC_METHOD(thread_tmp_fu_238_p4);
    sensitive << ( Ai_data_V );

    SC_METHOD(thread_trunc_ln1503_1_fu_88_p4);
    sensitive << ( Bi_data_V );

    SC_METHOD(thread_trunc_ln1503_2_fu_104_p4);
    sensitive << ( Ai_data_V );

    SC_METHOD(thread_trunc_ln1503_3_fu_114_p4);
    sensitive << ( Bi_data_V );

    SC_METHOD(thread_trunc_ln1503_4_fu_180_p4);
    sensitive << ( Ai_data_V );

    SC_METHOD(thread_trunc_ln1503_5_fu_222_p4);
    sensitive << ( Bi_data_V );

    SC_METHOD(thread_trunc_ln214_1_fu_134_p1);
    sensitive << ( Bi_data_V );

    SC_METHOD(thread_trunc_ln214_fu_130_p1);
    sensitive << ( Ai_data_V );

    SC_METHOD(thread_trunc_ln_fu_72_p4);
    sensitive << ( Ai_data_V );

    SC_METHOD(thread_xor_ln895_fu_380_p2);
    sensitive << ( icmp_ln895_fu_174_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "stitchNeighbors_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Ai_data_V, "(port)Ai_data_V");
    sc_trace(mVcdFile, Bi_data_V, "(port)Bi_data_V");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln_fu_72_p4, "trunc_ln_fu_72_p4");
    sc_trace(mVcdFile, trunc_ln1503_1_fu_88_p4, "trunc_ln1503_1_fu_88_p4");
    sc_trace(mVcdFile, trunc_ln1503_2_fu_104_p4, "trunc_ln1503_2_fu_104_p4");
    sc_trace(mVcdFile, trunc_ln1503_3_fu_114_p4, "trunc_ln1503_3_fu_114_p4");
    sc_trace(mVcdFile, trunc_ln214_fu_130_p1, "trunc_ln214_fu_130_p1");
    sc_trace(mVcdFile, trunc_ln214_1_fu_134_p1, "trunc_ln214_1_fu_134_p1");
    sc_trace(mVcdFile, rhs_V_fu_142_p1, "rhs_V_fu_142_p1");
    sc_trace(mVcdFile, lhs_V_fu_138_p1, "lhs_V_fu_138_p1");
    sc_trace(mVcdFile, ret_V_fu_146_p2, "ret_V_fu_146_p2");
    sc_trace(mVcdFile, tmp_2_fu_152_p3, "tmp_2_fu_152_p3");
    sc_trace(mVcdFile, pegged_cEtSum_V_fu_160_p2, "pegged_cEtSum_V_fu_160_p2");
    sc_trace(mVcdFile, trunc_ln1503_4_fu_180_p4, "trunc_ln1503_4_fu_180_p4");
    sc_trace(mVcdFile, lhs_V_1_fu_190_p1, "lhs_V_1_fu_190_p1");
    sc_trace(mVcdFile, ret_V_1_fu_194_p2, "ret_V_1_fu_194_p2");
    sc_trace(mVcdFile, tmp_3_fu_200_p3, "tmp_3_fu_200_p3");
    sc_trace(mVcdFile, pegged_tEtSum_V_fu_208_p2, "pegged_tEtSum_V_fu_208_p2");
    sc_trace(mVcdFile, trunc_ln1503_5_fu_222_p4, "trunc_ln1503_5_fu_222_p4");
    sc_trace(mVcdFile, tmp_fu_238_p4, "tmp_fu_238_p4");
    sc_trace(mVcdFile, pegged_tEtSum_V_1_fu_214_p3, "pegged_tEtSum_V_1_fu_214_p3");
    sc_trace(mVcdFile, pegged_cEtSum_V_1_fu_166_p3, "pegged_cEtSum_V_1_fu_166_p3");
    sc_trace(mVcdFile, tmp_1_fu_260_p4, "tmp_1_fu_260_p4");
    sc_trace(mVcdFile, tEt_leftOver_V_fu_232_p2, "tEt_leftOver_V_fu_232_p2");
    sc_trace(mVcdFile, lhs_V_2_fu_284_p1, "lhs_V_2_fu_284_p1");
    sc_trace(mVcdFile, ret_V_4_fu_288_p2, "ret_V_4_fu_288_p2");
    sc_trace(mVcdFile, tmp_4_fu_294_p3, "tmp_4_fu_294_p3");
    sc_trace(mVcdFile, pegged_tEtSum_V_2_fu_302_p2, "pegged_tEtSum_V_2_fu_302_p2");
    sc_trace(mVcdFile, tEt_leftOver_V_1_fu_316_p2, "tEt_leftOver_V_1_fu_316_p2");
    sc_trace(mVcdFile, tmp4_fu_322_p5, "tmp4_fu_322_p5");
    sc_trace(mVcdFile, pegged_tEtSum_V_3_fu_308_p3, "pegged_tEtSum_V_3_fu_308_p3");
    sc_trace(mVcdFile, icmp_ln879_1_fu_98_p2, "icmp_ln879_1_fu_98_p2");
    sc_trace(mVcdFile, phiStitch_fu_124_p2, "phiStitch_fu_124_p2");
    sc_trace(mVcdFile, and_ln879_fu_354_p2, "and_ln879_fu_354_p2");
    sc_trace(mVcdFile, icmp_ln879_fu_82_p2, "icmp_ln879_fu_82_p2");
    sc_trace(mVcdFile, and_ln879_1_fu_360_p2, "and_ln879_1_fu_360_p2");
    sc_trace(mVcdFile, icmp_ln895_fu_174_p2, "icmp_ln895_fu_174_p2");
    sc_trace(mVcdFile, and_ln895_fu_366_p2, "and_ln895_fu_366_p2");
    sc_trace(mVcdFile, ret_V_2_fu_248_p5, "ret_V_2_fu_248_p5");
    sc_trace(mVcdFile, xor_ln895_fu_380_p2, "xor_ln895_fu_380_p2");
    sc_trace(mVcdFile, and_ln895_1_fu_386_p2, "and_ln895_1_fu_386_p2");
    sc_trace(mVcdFile, ret_V_5_fu_334_p2, "ret_V_5_fu_334_p2");
    sc_trace(mVcdFile, select_ln895_fu_372_p3, "select_ln895_fu_372_p3");
    sc_trace(mVcdFile, ret_V_3_fu_270_p6, "ret_V_3_fu_270_p6");
    sc_trace(mVcdFile, ret_V_6_fu_340_p6, "ret_V_6_fu_340_p6");
    sc_trace(mVcdFile, select_ln895_2_fu_400_p3, "select_ln895_2_fu_400_p3");
    sc_trace(mVcdFile, select_ln895_1_fu_392_p3, "select_ln895_1_fu_392_p3");
    sc_trace(mVcdFile, select_ln895_3_fu_408_p3, "select_ln895_3_fu_408_p3");
#endif

    }
}

stitchNeighbors::~stitchNeighbors() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void stitchNeighbors::thread_and_ln879_1_fu_360_p2() {
    and_ln879_1_fu_360_p2 = (and_ln879_fu_354_p2.read() & icmp_ln879_fu_82_p2.read());
}

void stitchNeighbors::thread_and_ln879_fu_354_p2() {
    and_ln879_fu_354_p2 = (icmp_ln879_1_fu_98_p2.read() & phiStitch_fu_124_p2.read());
}

void stitchNeighbors::thread_and_ln895_1_fu_386_p2() {
    and_ln895_1_fu_386_p2 = (and_ln879_1_fu_360_p2.read() & xor_ln895_fu_380_p2.read());
}

void stitchNeighbors::thread_and_ln895_fu_366_p2() {
    and_ln895_fu_366_p2 = (and_ln879_1_fu_360_p2.read() & icmp_ln895_fu_174_p2.read());
}

void stitchNeighbors::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void stitchNeighbors::thread_ap_return_0() {
    ap_return_0 = select_ln895_1_fu_392_p3.read();
}

void stitchNeighbors::thread_ap_return_1() {
    ap_return_1 = select_ln895_3_fu_408_p3.read();
}

void stitchNeighbors::thread_icmp_ln879_1_fu_98_p2() {
    icmp_ln879_1_fu_98_p2 = (!trunc_ln1503_1_fu_88_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln1503_1_fu_88_p4.read() == ap_const_lv3_0);
}

void stitchNeighbors::thread_icmp_ln879_fu_82_p2() {
    icmp_ln879_fu_82_p2 = (!trunc_ln_fu_72_p4.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln_fu_72_p4.read() == ap_const_lv3_4);
}

void stitchNeighbors::thread_icmp_ln895_fu_174_p2() {
    icmp_ln895_fu_174_p2 = (!trunc_ln214_fu_130_p1.read().is_01() || !trunc_ln214_1_fu_134_p1.read().is_01())? sc_lv<1>(): (sc_biguint<10>(trunc_ln214_fu_130_p1.read()) > sc_biguint<10>(trunc_ln214_1_fu_134_p1.read()));
}

void stitchNeighbors::thread_lhs_V_1_fu_190_p1() {
    lhs_V_1_fu_190_p1 = esl_zext<11,10>(trunc_ln1503_4_fu_180_p4.read());
}

void stitchNeighbors::thread_lhs_V_2_fu_284_p1() {
    lhs_V_2_fu_284_p1 = esl_zext<11,10>(trunc_ln1503_5_fu_222_p4.read());
}

void stitchNeighbors::thread_lhs_V_fu_138_p1() {
    lhs_V_fu_138_p1 = esl_zext<11,10>(trunc_ln214_fu_130_p1.read());
}

void stitchNeighbors::thread_pegged_cEtSum_V_1_fu_166_p3() {
    pegged_cEtSum_V_1_fu_166_p3 = (!tmp_2_fu_152_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_2_fu_152_p3.read()[0].to_bool())? ap_const_lv10_3FF: pegged_cEtSum_V_fu_160_p2.read());
}

void stitchNeighbors::thread_pegged_cEtSum_V_fu_160_p2() {
    pegged_cEtSum_V_fu_160_p2 = (!trunc_ln214_fu_130_p1.read().is_01() || !trunc_ln214_1_fu_134_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln214_fu_130_p1.read()) + sc_biguint<10>(trunc_ln214_1_fu_134_p1.read()));
}

void stitchNeighbors::thread_pegged_tEtSum_V_1_fu_214_p3() {
    pegged_tEtSum_V_1_fu_214_p3 = (!tmp_3_fu_200_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_3_fu_200_p3.read()[0].to_bool())? ap_const_lv10_3FF: pegged_tEtSum_V_fu_208_p2.read());
}

void stitchNeighbors::thread_pegged_tEtSum_V_2_fu_302_p2() {
    pegged_tEtSum_V_2_fu_302_p2 = (!trunc_ln214_fu_130_p1.read().is_01() || !trunc_ln1503_5_fu_222_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln214_fu_130_p1.read()) + sc_biguint<10>(trunc_ln1503_5_fu_222_p4.read()));
}

void stitchNeighbors::thread_pegged_tEtSum_V_3_fu_308_p3() {
    pegged_tEtSum_V_3_fu_308_p3 = (!tmp_4_fu_294_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_4_fu_294_p3.read()[0].to_bool())? ap_const_lv10_3FF: pegged_tEtSum_V_2_fu_302_p2.read());
}

void stitchNeighbors::thread_pegged_tEtSum_V_fu_208_p2() {
    pegged_tEtSum_V_fu_208_p2 = (!trunc_ln214_1_fu_134_p1.read().is_01() || !trunc_ln1503_4_fu_180_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln214_1_fu_134_p1.read()) + sc_biguint<10>(trunc_ln1503_4_fu_180_p4.read()));
}

void stitchNeighbors::thread_phiStitch_fu_124_p2() {
    phiStitch_fu_124_p2 = (!trunc_ln1503_2_fu_104_p4.read().is_01() || !trunc_ln1503_3_fu_114_p4.read().is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln1503_2_fu_104_p4.read() == trunc_ln1503_3_fu_114_p4.read());
}

void stitchNeighbors::thread_ret_V_1_fu_194_p2() {
    ret_V_1_fu_194_p2 = (!lhs_V_1_fu_190_p1.read().is_01() || !rhs_V_fu_142_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(lhs_V_1_fu_190_p1.read()) + sc_biguint<11>(rhs_V_fu_142_p1.read()));
}

void stitchNeighbors::thread_ret_V_2_fu_248_p5() {
    ret_V_2_fu_248_p5 = esl_concat<22,10>(esl_concat<12,10>(esl_concat<9,3>(tmp_fu_238_p4.read(), ap_const_lv3_4), pegged_tEtSum_V_1_fu_214_p3.read()), pegged_cEtSum_V_1_fu_166_p3.read());
}

void stitchNeighbors::thread_ret_V_3_fu_270_p6() {
    ret_V_3_fu_270_p6 = esl_concat<22,10>(esl_concat<12,10>(esl_concat<9,3>(esl_concat<6,3>(tmp_1_fu_260_p4.read(), trunc_ln1503_2_fu_104_p4.read()), ap_const_lv3_0), tEt_leftOver_V_fu_232_p2.read()), ap_const_lv10_0);
}

void stitchNeighbors::thread_ret_V_4_fu_288_p2() {
    ret_V_4_fu_288_p2 = (!lhs_V_2_fu_284_p1.read().is_01() || !lhs_V_fu_138_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(lhs_V_2_fu_284_p1.read()) + sc_biguint<11>(lhs_V_fu_138_p1.read()));
}

void stitchNeighbors::thread_ret_V_5_fu_334_p2() {
    ret_V_5_fu_334_p2 = (tmp4_fu_322_p5.read() | ap_const_lv32_400000);
}

void stitchNeighbors::thread_ret_V_6_fu_340_p6() {
    ret_V_6_fu_340_p6 = esl_concat<22,10>(esl_concat<12,10>(esl_concat<9,3>(esl_concat<6,3>(tmp_1_fu_260_p4.read(), trunc_ln1503_2_fu_104_p4.read()), ap_const_lv3_0), pegged_tEtSum_V_3_fu_308_p3.read()), pegged_cEtSum_V_1_fu_166_p3.read());
}

void stitchNeighbors::thread_ret_V_fu_146_p2() {
    ret_V_fu_146_p2 = (!rhs_V_fu_142_p1.read().is_01() || !lhs_V_fu_138_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(rhs_V_fu_142_p1.read()) + sc_biguint<11>(lhs_V_fu_138_p1.read()));
}

void stitchNeighbors::thread_rhs_V_fu_142_p1() {
    rhs_V_fu_142_p1 = esl_zext<11,10>(trunc_ln214_1_fu_134_p1.read());
}

void stitchNeighbors::thread_select_ln895_1_fu_392_p3() {
    select_ln895_1_fu_392_p3 = (!and_ln895_1_fu_386_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln895_1_fu_386_p2.read()[0].to_bool())? ret_V_5_fu_334_p2.read(): select_ln895_fu_372_p3.read());
}

void stitchNeighbors::thread_select_ln895_2_fu_400_p3() {
    select_ln895_2_fu_400_p3 = (!and_ln895_fu_366_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln895_fu_366_p2.read()[0].to_bool())? ret_V_3_fu_270_p6.read(): Bi_data_V.read());
}

void stitchNeighbors::thread_select_ln895_3_fu_408_p3() {
    select_ln895_3_fu_408_p3 = (!and_ln895_1_fu_386_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln895_1_fu_386_p2.read()[0].to_bool())? ret_V_6_fu_340_p6.read(): select_ln895_2_fu_400_p3.read());
}

void stitchNeighbors::thread_select_ln895_fu_372_p3() {
    select_ln895_fu_372_p3 = (!and_ln895_fu_366_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln895_fu_366_p2.read()[0].to_bool())? ret_V_2_fu_248_p5.read(): Ai_data_V.read());
}

void stitchNeighbors::thread_tEt_leftOver_V_1_fu_316_p2() {
    tEt_leftOver_V_1_fu_316_p2 = (!trunc_ln1503_4_fu_180_p4.read().is_01() || !trunc_ln214_fu_130_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln1503_4_fu_180_p4.read()) - sc_biguint<10>(trunc_ln214_fu_130_p1.read()));
}

void stitchNeighbors::thread_tEt_leftOver_V_fu_232_p2() {
    tEt_leftOver_V_fu_232_p2 = (!trunc_ln1503_5_fu_222_p4.read().is_01() || !trunc_ln214_1_fu_134_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(trunc_ln1503_5_fu_222_p4.read()) - sc_biguint<10>(trunc_ln214_1_fu_134_p1.read()));
}

void stitchNeighbors::thread_tmp4_fu_322_p5() {
    tmp4_fu_322_p5 = esl_concat<22,10>(esl_concat<12,10>(esl_concat<9,3>(tmp_fu_238_p4.read(), ap_const_lv3_0), tEt_leftOver_V_1_fu_316_p2.read()), ap_const_lv10_0);
}

void stitchNeighbors::thread_tmp_1_fu_260_p4() {
    tmp_1_fu_260_p4 = Bi_data_V.read().range(31, 26);
}

void stitchNeighbors::thread_tmp_2_fu_152_p3() {
    tmp_2_fu_152_p3 = ret_V_fu_146_p2.read().range(10, 10);
}

void stitchNeighbors::thread_tmp_3_fu_200_p3() {
    tmp_3_fu_200_p3 = ret_V_1_fu_194_p2.read().range(10, 10);
}

void stitchNeighbors::thread_tmp_4_fu_294_p3() {
    tmp_4_fu_294_p3 = ret_V_4_fu_288_p2.read().range(10, 10);
}

void stitchNeighbors::thread_tmp_fu_238_p4() {
    tmp_fu_238_p4 = Ai_data_V.read().range(31, 23);
}

void stitchNeighbors::thread_trunc_ln1503_1_fu_88_p4() {
    trunc_ln1503_1_fu_88_p4 = Bi_data_V.read().range(22, 20);
}

void stitchNeighbors::thread_trunc_ln1503_2_fu_104_p4() {
    trunc_ln1503_2_fu_104_p4 = Ai_data_V.read().range(25, 23);
}

void stitchNeighbors::thread_trunc_ln1503_3_fu_114_p4() {
    trunc_ln1503_3_fu_114_p4 = Bi_data_V.read().range(25, 23);
}

void stitchNeighbors::thread_trunc_ln1503_4_fu_180_p4() {
    trunc_ln1503_4_fu_180_p4 = Ai_data_V.read().range(19, 10);
}

void stitchNeighbors::thread_trunc_ln1503_5_fu_222_p4() {
    trunc_ln1503_5_fu_222_p4 = Bi_data_V.read().range(19, 10);
}

void stitchNeighbors::thread_trunc_ln214_1_fu_134_p1() {
    trunc_ln214_1_fu_134_p1 = Bi_data_V.read().range(10-1, 0);
}

void stitchNeighbors::thread_trunc_ln214_fu_130_p1() {
    trunc_ln214_fu_130_p1 = Ai_data_V.read().range(10-1, 0);
}

void stitchNeighbors::thread_trunc_ln_fu_72_p4() {
    trunc_ln_fu_72_p4 = Ai_data_V.read().range(22, 20);
}

void stitchNeighbors::thread_xor_ln895_fu_380_p2() {
    xor_ln895_fu_380_p2 = (icmp_ln895_fu_174_p2.read() ^ ap_const_lv1_1);
}

}

