// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stitchInPhi (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
input  [31:0] p_read32;
input  [31:0] p_read33;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;
output  [31:0] ap_return_16;
output  [31:0] ap_return_17;
output  [31:0] ap_return_18;
output  [31:0] ap_return_19;
output  [31:0] ap_return_20;
output  [31:0] ap_return_21;
output  [31:0] ap_return_22;
output  [31:0] ap_return_23;
output  [31:0] ap_return_24;
output  [31:0] ap_return_25;
output  [31:0] ap_return_26;
output  [31:0] ap_return_27;
output  [31:0] ap_return_28;
output  [31:0] ap_return_29;
output  [31:0] ap_return_30;
output  [31:0] ap_return_31;
output  [31:0] ap_return_32;
output  [31:0] ap_return_33;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] towersy_0_tower_0_s_reg_538;
reg   [31:0] towersy_1_tower_0_s_reg_543;
reg   [31:0] towersy_0_tower_1_s_reg_548;
reg   [31:0] towersy_1_tower_1_s_reg_553;
reg   [31:0] towersy_0_tower_2_s_reg_558;
reg   [31:0] towersy_1_tower_2_s_reg_563;
reg   [31:0] towersy_0_tower_3_s_reg_568;
wire    ap_CS_fsm_state2;
reg   [31:0] towersy_1_tower_3_s_reg_573;
reg   [31:0] towersy_0_tower_4_s_reg_578;
reg   [31:0] towersy_1_tower_4_s_reg_583;
reg   [31:0] towersy_0_tower_5_s_reg_588;
reg   [31:0] towersy_1_tower_5_s_reg_593;
reg   [31:0] towersy_0_tower_6_s_reg_598;
wire    ap_CS_fsm_state3;
reg   [31:0] towersy_1_tower_6_s_reg_603;
reg   [31:0] towersy_0_tower_7_s_reg_608;
reg   [31:0] towersy_1_tower_7_s_reg_613;
reg   [31:0] towersy_0_tower_8_s_reg_618;
reg   [31:0] towersy_1_tower_8_s_reg_623;
reg   [31:0] towersy_0_tower_9_s_reg_628;
wire    ap_CS_fsm_state4;
reg   [31:0] towersy_1_tower_9_s_reg_633;
reg   [31:0] towersy_0_tower_10_reg_638;
reg   [31:0] towersy_1_tower_10_reg_643;
reg   [31:0] towersy_0_tower_11_reg_648;
reg   [31:0] towersy_1_tower_11_reg_653;
reg   [31:0] towersy_0_tower_12_reg_658;
wire    ap_CS_fsm_state5;
reg   [31:0] towersy_1_tower_12_reg_663;
reg   [31:0] towersy_0_tower_13_reg_668;
reg   [31:0] towersy_1_tower_13_reg_673;
reg   [31:0] towersy_0_tower_14_reg_678;
reg   [31:0] towersy_1_tower_14_reg_683;
reg   [31:0] ap_port_reg_p_read3;
reg   [31:0] ap_port_reg_p_read4;
reg   [31:0] ap_port_reg_p_read5;
reg   [31:0] ap_port_reg_p_read6;
reg   [31:0] ap_port_reg_p_read7;
reg   [31:0] ap_port_reg_p_read8;
reg   [31:0] ap_port_reg_p_read9;
reg   [31:0] ap_port_reg_p_read10;
reg   [31:0] ap_port_reg_p_read11;
reg   [31:0] ap_port_reg_p_read12;
reg   [31:0] ap_port_reg_p_read13;
reg   [31:0] ap_port_reg_p_read14;
reg   [31:0] ap_port_reg_p_read15;
reg   [31:0] ap_port_reg_p_read16;
reg   [31:0] ap_port_reg_p_read20;
reg   [31:0] ap_port_reg_p_read21;
reg   [31:0] ap_port_reg_p_read22;
reg   [31:0] ap_port_reg_p_read23;
reg   [31:0] ap_port_reg_p_read24;
reg   [31:0] ap_port_reg_p_read25;
reg   [31:0] ap_port_reg_p_read26;
reg   [31:0] ap_port_reg_p_read27;
reg   [31:0] ap_port_reg_p_read28;
reg   [31:0] ap_port_reg_p_read29;
reg   [31:0] ap_port_reg_p_read30;
reg   [31:0] ap_port_reg_p_read31;
reg   [31:0] ap_port_reg_p_read32;
reg   [31:0] ap_port_reg_p_read33;
wire    grp_stitchNeighbors_fu_288_ap_ready;
reg   [31:0] grp_stitchNeighbors_fu_288_Ai_data_V;
reg   [31:0] grp_stitchNeighbors_fu_288_Bi_data_V;
wire   [31:0] grp_stitchNeighbors_fu_288_ap_return_0;
wire   [31:0] grp_stitchNeighbors_fu_288_ap_return_1;
wire    grp_stitchNeighbors_fu_296_ap_ready;
reg   [31:0] grp_stitchNeighbors_fu_296_Ai_data_V;
reg   [31:0] grp_stitchNeighbors_fu_296_Bi_data_V;
wire   [31:0] grp_stitchNeighbors_fu_296_ap_return_0;
wire   [31:0] grp_stitchNeighbors_fu_296_ap_return_1;
wire    grp_stitchNeighbors_fu_304_ap_ready;
reg   [31:0] grp_stitchNeighbors_fu_304_Ai_data_V;
reg   [31:0] grp_stitchNeighbors_fu_304_Bi_data_V;
wire   [31:0] grp_stitchNeighbors_fu_304_ap_return_0;
wire   [31:0] grp_stitchNeighbors_fu_304_ap_return_1;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

stitchNeighbors grp_stitchNeighbors_fu_288(
    .ap_ready(grp_stitchNeighbors_fu_288_ap_ready),
    .Ai_data_V(grp_stitchNeighbors_fu_288_Ai_data_V),
    .Bi_data_V(grp_stitchNeighbors_fu_288_Bi_data_V),
    .ap_return_0(grp_stitchNeighbors_fu_288_ap_return_0),
    .ap_return_1(grp_stitchNeighbors_fu_288_ap_return_1)
);

stitchNeighbors grp_stitchNeighbors_fu_296(
    .ap_ready(grp_stitchNeighbors_fu_296_ap_ready),
    .Ai_data_V(grp_stitchNeighbors_fu_296_Ai_data_V),
    .Bi_data_V(grp_stitchNeighbors_fu_296_Bi_data_V),
    .ap_return_0(grp_stitchNeighbors_fu_296_ap_return_0),
    .ap_return_1(grp_stitchNeighbors_fu_296_ap_return_1)
);

stitchNeighbors grp_stitchNeighbors_fu_304(
    .ap_ready(grp_stitchNeighbors_fu_304_ap_ready),
    .Ai_data_V(grp_stitchNeighbors_fu_304_Ai_data_V),
    .Bi_data_V(grp_stitchNeighbors_fu_304_Bi_data_V),
    .ap_return_0(grp_stitchNeighbors_fu_304_ap_return_0),
    .ap_return_1(grp_stitchNeighbors_fu_304_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_p_read10 <= p_read10;
        ap_port_reg_p_read11 <= p_read11;
        ap_port_reg_p_read12 <= p_read12;
        ap_port_reg_p_read13 <= p_read13;
        ap_port_reg_p_read14 <= p_read14;
        ap_port_reg_p_read15 <= p_read15;
        ap_port_reg_p_read16 <= p_read16;
        ap_port_reg_p_read20 <= p_read20;
        ap_port_reg_p_read21 <= p_read21;
        ap_port_reg_p_read22 <= p_read22;
        ap_port_reg_p_read23 <= p_read23;
        ap_port_reg_p_read24 <= p_read24;
        ap_port_reg_p_read25 <= p_read25;
        ap_port_reg_p_read26 <= p_read26;
        ap_port_reg_p_read27 <= p_read27;
        ap_port_reg_p_read28 <= p_read28;
        ap_port_reg_p_read29 <= p_read29;
        ap_port_reg_p_read3 <= p_read3;
        ap_port_reg_p_read30 <= p_read30;
        ap_port_reg_p_read31 <= p_read31;
        ap_port_reg_p_read32 <= p_read32;
        ap_port_reg_p_read33 <= p_read33;
        ap_port_reg_p_read4 <= p_read4;
        ap_port_reg_p_read5 <= p_read5;
        ap_port_reg_p_read6 <= p_read6;
        ap_port_reg_p_read7 <= p_read7;
        ap_port_reg_p_read8 <= p_read8;
        ap_port_reg_p_read9 <= p_read9;
        towersy_0_tower_0_s_reg_538 <= grp_stitchNeighbors_fu_288_ap_return_0;
        towersy_0_tower_1_s_reg_548 <= grp_stitchNeighbors_fu_296_ap_return_0;
        towersy_0_tower_2_s_reg_558 <= grp_stitchNeighbors_fu_304_ap_return_0;
        towersy_1_tower_0_s_reg_543 <= grp_stitchNeighbors_fu_288_ap_return_1;
        towersy_1_tower_1_s_reg_553 <= grp_stitchNeighbors_fu_296_ap_return_1;
        towersy_1_tower_2_s_reg_563 <= grp_stitchNeighbors_fu_304_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
        towersy_0_tower_10_reg_638 <= grp_stitchNeighbors_fu_296_ap_return_0;
        towersy_0_tower_11_reg_648 <= grp_stitchNeighbors_fu_304_ap_return_0;
        towersy_0_tower_9_s_reg_628 <= grp_stitchNeighbors_fu_288_ap_return_0;
        towersy_1_tower_10_reg_643 <= grp_stitchNeighbors_fu_296_ap_return_1;
        towersy_1_tower_11_reg_653 <= grp_stitchNeighbors_fu_304_ap_return_1;
        towersy_1_tower_9_s_reg_633 <= grp_stitchNeighbors_fu_288_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
        towersy_0_tower_12_reg_658 <= grp_stitchNeighbors_fu_288_ap_return_0;
        towersy_0_tower_13_reg_668 <= grp_stitchNeighbors_fu_296_ap_return_0;
        towersy_0_tower_14_reg_678 <= grp_stitchNeighbors_fu_304_ap_return_0;
        towersy_1_tower_12_reg_663 <= grp_stitchNeighbors_fu_288_ap_return_1;
        towersy_1_tower_13_reg_673 <= grp_stitchNeighbors_fu_296_ap_return_1;
        towersy_1_tower_14_reg_683 <= grp_stitchNeighbors_fu_304_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        towersy_0_tower_3_s_reg_568 <= grp_stitchNeighbors_fu_288_ap_return_0;
        towersy_0_tower_4_s_reg_578 <= grp_stitchNeighbors_fu_296_ap_return_0;
        towersy_0_tower_5_s_reg_588 <= grp_stitchNeighbors_fu_304_ap_return_0;
        towersy_1_tower_3_s_reg_573 <= grp_stitchNeighbors_fu_288_ap_return_1;
        towersy_1_tower_4_s_reg_583 <= grp_stitchNeighbors_fu_296_ap_return_1;
        towersy_1_tower_5_s_reg_593 <= grp_stitchNeighbors_fu_304_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
        towersy_0_tower_6_s_reg_598 <= grp_stitchNeighbors_fu_288_ap_return_0;
        towersy_0_tower_7_s_reg_608 <= grp_stitchNeighbors_fu_296_ap_return_0;
        towersy_0_tower_8_s_reg_618 <= grp_stitchNeighbors_fu_304_ap_return_0;
        towersy_1_tower_6_s_reg_603 <= grp_stitchNeighbors_fu_288_ap_return_1;
        towersy_1_tower_7_s_reg_613 <= grp_stitchNeighbors_fu_296_ap_return_1;
        towersy_1_tower_8_s_reg_623 <= grp_stitchNeighbors_fu_304_ap_return_1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = ap_port_reg_p_read15;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = ap_port_reg_p_read12;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = ap_port_reg_p_read9;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = ap_port_reg_p_read6;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = ap_port_reg_p_read3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_288_Ai_data_V = p_read;
    end else begin
        grp_stitchNeighbors_fu_288_Ai_data_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = ap_port_reg_p_read32;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = ap_port_reg_p_read29;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = ap_port_reg_p_read26;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = ap_port_reg_p_read23;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = ap_port_reg_p_read20;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_288_Bi_data_V = p_read17;
    end else begin
        grp_stitchNeighbors_fu_288_Bi_data_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = ap_port_reg_p_read16;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = ap_port_reg_p_read13;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = ap_port_reg_p_read10;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = ap_port_reg_p_read7;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = ap_port_reg_p_read4;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_296_Ai_data_V = p_read1;
    end else begin
        grp_stitchNeighbors_fu_296_Ai_data_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = ap_port_reg_p_read33;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = ap_port_reg_p_read30;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = ap_port_reg_p_read27;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = ap_port_reg_p_read24;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = ap_port_reg_p_read21;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_296_Bi_data_V = p_read18;
    end else begin
        grp_stitchNeighbors_fu_296_Bi_data_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_304_Ai_data_V = ap_port_reg_p_read14;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_304_Ai_data_V = ap_port_reg_p_read11;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_304_Ai_data_V = ap_port_reg_p_read8;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_304_Ai_data_V = ap_port_reg_p_read5;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_304_Ai_data_V = p_read2;
    end else begin
        grp_stitchNeighbors_fu_304_Ai_data_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_stitchNeighbors_fu_304_Bi_data_V = ap_port_reg_p_read31;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_stitchNeighbors_fu_304_Bi_data_V = ap_port_reg_p_read28;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_stitchNeighbors_fu_304_Bi_data_V = ap_port_reg_p_read25;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_stitchNeighbors_fu_304_Bi_data_V = ap_port_reg_p_read22;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_stitchNeighbors_fu_304_Bi_data_V = p_read19;
    end else begin
        grp_stitchNeighbors_fu_304_Bi_data_V = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return_0 = towersy_0_tower_0_s_reg_538;

assign ap_return_1 = towersy_0_tower_1_s_reg_548;

assign ap_return_10 = towersy_0_tower_10_reg_638;

assign ap_return_11 = towersy_0_tower_11_reg_648;

assign ap_return_12 = towersy_0_tower_12_reg_658;

assign ap_return_13 = towersy_0_tower_13_reg_668;

assign ap_return_14 = towersy_0_tower_14_reg_678;

assign ap_return_15 = grp_stitchNeighbors_fu_288_ap_return_0;

assign ap_return_16 = grp_stitchNeighbors_fu_296_ap_return_0;

assign ap_return_17 = towersy_1_tower_0_s_reg_543;

assign ap_return_18 = towersy_1_tower_1_s_reg_553;

assign ap_return_19 = towersy_1_tower_2_s_reg_563;

assign ap_return_2 = towersy_0_tower_2_s_reg_558;

assign ap_return_20 = towersy_1_tower_3_s_reg_573;

assign ap_return_21 = towersy_1_tower_4_s_reg_583;

assign ap_return_22 = towersy_1_tower_5_s_reg_593;

assign ap_return_23 = towersy_1_tower_6_s_reg_603;

assign ap_return_24 = towersy_1_tower_7_s_reg_613;

assign ap_return_25 = towersy_1_tower_8_s_reg_623;

assign ap_return_26 = towersy_1_tower_9_s_reg_633;

assign ap_return_27 = towersy_1_tower_10_reg_643;

assign ap_return_28 = towersy_1_tower_11_reg_653;

assign ap_return_29 = towersy_1_tower_12_reg_663;

assign ap_return_3 = towersy_0_tower_3_s_reg_568;

assign ap_return_30 = towersy_1_tower_13_reg_673;

assign ap_return_31 = towersy_1_tower_14_reg_683;

assign ap_return_32 = grp_stitchNeighbors_fu_288_ap_return_1;

assign ap_return_33 = grp_stitchNeighbors_fu_296_ap_return_1;

assign ap_return_4 = towersy_0_tower_4_s_reg_578;

assign ap_return_5 = towersy_0_tower_5_s_reg_588;

assign ap_return_6 = towersy_0_tower_6_s_reg_598;

assign ap_return_7 = towersy_0_tower_7_s_reg_608;

assign ap_return_8 = towersy_0_tower_8_s_reg_618;

assign ap_return_9 = towersy_0_tower_9_s_reg_628;

endmodule //stitchInPhi
