// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _stitchNeighbors_HH_
#define _stitchNeighbors_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct stitchNeighbors : public sc_module {
    // Port declarations 5
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > Ai_data_V;
    sc_in< sc_lv<32> > Bi_data_V;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;


    // Module declarations
    stitchNeighbors(sc_module_name name);
    SC_HAS_PROCESS(stitchNeighbors);

    ~stitchNeighbors();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<3> > trunc_ln_fu_74_p4;
    sc_signal< sc_lv<3> > trunc_ln1503_1_fu_90_p4;
    sc_signal< sc_lv<3> > trunc_ln1503_2_fu_106_p4;
    sc_signal< sc_lv<3> > trunc_ln1503_3_fu_116_p4;
    sc_signal< sc_lv<10> > trunc_ln214_fu_132_p1;
    sc_signal< sc_lv<10> > trunc_ln214_1_fu_146_p1;
    sc_signal< sc_lv<11> > lhs_V_fu_160_p1;
    sc_signal< sc_lv<11> > rhs_V_fu_164_p1;
    sc_signal< sc_lv<11> > ret_V_fu_168_p2;
    sc_signal< sc_lv<9> > tmp_2_fu_188_p4;
    sc_signal< sc_lv<10> > trunc_ln1503_4_fu_136_p4;
    sc_signal< sc_lv<32> > or_ln1356_2_fu_198_p5;
    sc_signal< sc_lv<10> > add_ln209_fu_222_p2;
    sc_signal< sc_lv<6> > tmp_5_fu_240_p4;
    sc_signal< sc_lv<10> > trunc_ln1503_8_fu_150_p4;
    sc_signal< sc_lv<32> > ret_V_6_fu_250_p6;
    sc_signal< sc_lv<1> > tmp_fu_180_p3;
    sc_signal< sc_lv<32> > ret_V_2_fu_216_p2;
    sc_signal< sc_lv<32> > ret_V_3_fu_228_p5;
    sc_signal< sc_lv<1> > icmp_ln879_1_fu_100_p2;
    sc_signal< sc_lv<1> > phiStitch_fu_126_p2;
    sc_signal< sc_lv<1> > and_ln879_fu_292_p2;
    sc_signal< sc_lv<1> > icmp_ln879_fu_84_p2;
    sc_signal< sc_lv<1> > and_ln879_1_fu_298_p2;
    sc_signal< sc_lv<1> > icmp_ln895_fu_174_p2;
    sc_signal< sc_lv<1> > and_ln895_fu_304_p2;
    sc_signal< sc_lv<32> > select_ln895_fu_284_p3;
    sc_signal< sc_lv<32> > ret_V_1_fu_210_p2;
    sc_signal< sc_lv<1> > xor_ln895_fu_318_p2;
    sc_signal< sc_lv<1> > and_ln895_1_fu_324_p2;
    sc_signal< sc_lv<1> > and_ln895_2_fu_330_p2;
    sc_signal< sc_lv<32> > select_ln895_1_fu_310_p3;
    sc_signal< sc_lv<32> > select_ln895_2_fu_336_p3;
    sc_signal< sc_lv<32> > ret_V_5_fu_270_p6;
    sc_signal< sc_lv<32> > ret_V_4_fu_264_p2;
    sc_signal< sc_lv<32> > select_ln895_3_fu_352_p3;
    sc_signal< sc_lv<32> > select_ln895_4_fu_360_p3;
    sc_signal< sc_lv<32> > select_ln879_fu_344_p3;
    sc_signal< sc_lv<32> > select_ln879_1_fu_368_p3;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_400000;
    static const sc_lv<32> ap_const_lv32_4003FF;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_3FF;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln209_fu_222_p2();
    void thread_and_ln879_1_fu_298_p2();
    void thread_and_ln879_fu_292_p2();
    void thread_and_ln895_1_fu_324_p2();
    void thread_and_ln895_2_fu_330_p2();
    void thread_and_ln895_fu_304_p2();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_icmp_ln879_1_fu_100_p2();
    void thread_icmp_ln879_fu_84_p2();
    void thread_icmp_ln895_fu_174_p2();
    void thread_lhs_V_fu_160_p1();
    void thread_or_ln1356_2_fu_198_p5();
    void thread_phiStitch_fu_126_p2();
    void thread_ret_V_1_fu_210_p2();
    void thread_ret_V_2_fu_216_p2();
    void thread_ret_V_3_fu_228_p5();
    void thread_ret_V_4_fu_264_p2();
    void thread_ret_V_5_fu_270_p6();
    void thread_ret_V_6_fu_250_p6();
    void thread_ret_V_fu_168_p2();
    void thread_rhs_V_fu_164_p1();
    void thread_select_ln879_1_fu_368_p3();
    void thread_select_ln879_fu_344_p3();
    void thread_select_ln895_1_fu_310_p3();
    void thread_select_ln895_2_fu_336_p3();
    void thread_select_ln895_3_fu_352_p3();
    void thread_select_ln895_4_fu_360_p3();
    void thread_select_ln895_fu_284_p3();
    void thread_tmp_2_fu_188_p4();
    void thread_tmp_5_fu_240_p4();
    void thread_tmp_fu_180_p3();
    void thread_trunc_ln1503_1_fu_90_p4();
    void thread_trunc_ln1503_2_fu_106_p4();
    void thread_trunc_ln1503_3_fu_116_p4();
    void thread_trunc_ln1503_4_fu_136_p4();
    void thread_trunc_ln1503_8_fu_150_p4();
    void thread_trunc_ln214_1_fu_146_p1();
    void thread_trunc_ln214_fu_132_p1();
    void thread_trunc_ln_fu_74_p4();
    void thread_xor_ln895_fu_318_p2();
};

}

using namespace ap_rtl;

#endif
