// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _stitchInPhi_HH_
#define _stitchInPhi_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "stitchNeighbors.h"

namespace ap_rtl {

struct stitchInPhi : public sc_module {
    // Port declarations 69
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > p_read;
    sc_in< sc_lv<32> > p_read1;
    sc_in< sc_lv<32> > p_read2;
    sc_in< sc_lv<32> > p_read3;
    sc_in< sc_lv<32> > p_read4;
    sc_in< sc_lv<32> > p_read5;
    sc_in< sc_lv<32> > p_read6;
    sc_in< sc_lv<32> > p_read7;
    sc_in< sc_lv<32> > p_read8;
    sc_in< sc_lv<32> > p_read9;
    sc_in< sc_lv<32> > p_read10;
    sc_in< sc_lv<32> > p_read11;
    sc_in< sc_lv<32> > p_read12;
    sc_in< sc_lv<32> > p_read13;
    sc_in< sc_lv<32> > p_read14;
    sc_in< sc_lv<32> > p_read15;
    sc_in< sc_lv<32> > p_read16;
    sc_in< sc_lv<32> > p_read17;
    sc_in< sc_lv<32> > p_read18;
    sc_in< sc_lv<32> > p_read19;
    sc_in< sc_lv<32> > p_read20;
    sc_in< sc_lv<32> > p_read21;
    sc_in< sc_lv<32> > p_read22;
    sc_in< sc_lv<32> > p_read23;
    sc_in< sc_lv<32> > p_read24;
    sc_in< sc_lv<32> > p_read25;
    sc_in< sc_lv<32> > p_read26;
    sc_in< sc_lv<32> > p_read27;
    sc_in< sc_lv<32> > p_read28;
    sc_in< sc_lv<32> > p_read29;
    sc_in< sc_lv<32> > p_read30;
    sc_in< sc_lv<32> > p_read31;
    sc_in< sc_lv<32> > p_read32;
    sc_in< sc_lv<32> > p_read33;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_out< sc_lv<32> > ap_return_2;
    sc_out< sc_lv<32> > ap_return_3;
    sc_out< sc_lv<32> > ap_return_4;
    sc_out< sc_lv<32> > ap_return_5;
    sc_out< sc_lv<32> > ap_return_6;
    sc_out< sc_lv<32> > ap_return_7;
    sc_out< sc_lv<32> > ap_return_8;
    sc_out< sc_lv<32> > ap_return_9;
    sc_out< sc_lv<32> > ap_return_10;
    sc_out< sc_lv<32> > ap_return_11;
    sc_out< sc_lv<32> > ap_return_12;
    sc_out< sc_lv<32> > ap_return_13;
    sc_out< sc_lv<32> > ap_return_14;
    sc_out< sc_lv<32> > ap_return_15;
    sc_out< sc_lv<32> > ap_return_16;
    sc_out< sc_lv<32> > ap_return_17;
    sc_out< sc_lv<32> > ap_return_18;
    sc_out< sc_lv<32> > ap_return_19;
    sc_out< sc_lv<32> > ap_return_20;
    sc_out< sc_lv<32> > ap_return_21;
    sc_out< sc_lv<32> > ap_return_22;
    sc_out< sc_lv<32> > ap_return_23;
    sc_out< sc_lv<32> > ap_return_24;
    sc_out< sc_lv<32> > ap_return_25;
    sc_out< sc_lv<32> > ap_return_26;
    sc_out< sc_lv<32> > ap_return_27;
    sc_out< sc_lv<32> > ap_return_28;
    sc_out< sc_lv<32> > ap_return_29;
    sc_out< sc_lv<32> > ap_return_30;
    sc_out< sc_lv<32> > ap_return_31;
    sc_out< sc_lv<32> > ap_return_32;
    sc_out< sc_lv<32> > ap_return_33;


    // Module declarations
    stitchInPhi(sc_module_name name);
    SC_HAS_PROCESS(stitchInPhi);

    ~stitchInPhi();

    sc_trace_file* mVcdFile;

    stitchNeighbors* call_ret1_stitchNeighbors_fu_288;
    stitchNeighbors* call_ret2_stitchNeighbors_fu_296;
    stitchNeighbors* call_ret3_stitchNeighbors_fu_304;
    stitchNeighbors* call_ret4_stitchNeighbors_fu_312;
    stitchNeighbors* call_ret5_stitchNeighbors_fu_320;
    stitchNeighbors* call_ret6_stitchNeighbors_fu_328;
    stitchNeighbors* call_ret7_stitchNeighbors_fu_336;
    stitchNeighbors* call_ret8_stitchNeighbors_fu_344;
    stitchNeighbors* call_ret9_stitchNeighbors_fu_352;
    stitchNeighbors* call_ret10_stitchNeighbors_fu_360;
    stitchNeighbors* call_ret11_stitchNeighbors_fu_368;
    stitchNeighbors* call_ret12_stitchNeighbors_fu_376;
    stitchNeighbors* call_ret13_stitchNeighbors_fu_384;
    stitchNeighbors* call_ret14_stitchNeighbors_fu_392;
    stitchNeighbors* call_ret15_stitchNeighbors_fu_400;
    stitchNeighbors* call_ret16_stitchNeighbors_fu_408;
    stitchNeighbors* call_ret_stitchNeighbors_fu_416;
    sc_signal< sc_logic > call_ret1_stitchNeighbors_fu_288_ap_ready;
    sc_signal< sc_lv<32> > call_ret1_stitchNeighbors_fu_288_ap_return_0;
    sc_signal< sc_lv<32> > call_ret1_stitchNeighbors_fu_288_ap_return_1;
    sc_signal< sc_logic > call_ret2_stitchNeighbors_fu_296_ap_ready;
    sc_signal< sc_lv<32> > call_ret2_stitchNeighbors_fu_296_ap_return_0;
    sc_signal< sc_lv<32> > call_ret2_stitchNeighbors_fu_296_ap_return_1;
    sc_signal< sc_logic > call_ret3_stitchNeighbors_fu_304_ap_ready;
    sc_signal< sc_lv<32> > call_ret3_stitchNeighbors_fu_304_ap_return_0;
    sc_signal< sc_lv<32> > call_ret3_stitchNeighbors_fu_304_ap_return_1;
    sc_signal< sc_logic > call_ret4_stitchNeighbors_fu_312_ap_ready;
    sc_signal< sc_lv<32> > call_ret4_stitchNeighbors_fu_312_ap_return_0;
    sc_signal< sc_lv<32> > call_ret4_stitchNeighbors_fu_312_ap_return_1;
    sc_signal< sc_logic > call_ret5_stitchNeighbors_fu_320_ap_ready;
    sc_signal< sc_lv<32> > call_ret5_stitchNeighbors_fu_320_ap_return_0;
    sc_signal< sc_lv<32> > call_ret5_stitchNeighbors_fu_320_ap_return_1;
    sc_signal< sc_logic > call_ret6_stitchNeighbors_fu_328_ap_ready;
    sc_signal< sc_lv<32> > call_ret6_stitchNeighbors_fu_328_ap_return_0;
    sc_signal< sc_lv<32> > call_ret6_stitchNeighbors_fu_328_ap_return_1;
    sc_signal< sc_logic > call_ret7_stitchNeighbors_fu_336_ap_ready;
    sc_signal< sc_lv<32> > call_ret7_stitchNeighbors_fu_336_ap_return_0;
    sc_signal< sc_lv<32> > call_ret7_stitchNeighbors_fu_336_ap_return_1;
    sc_signal< sc_logic > call_ret8_stitchNeighbors_fu_344_ap_ready;
    sc_signal< sc_lv<32> > call_ret8_stitchNeighbors_fu_344_ap_return_0;
    sc_signal< sc_lv<32> > call_ret8_stitchNeighbors_fu_344_ap_return_1;
    sc_signal< sc_logic > call_ret9_stitchNeighbors_fu_352_ap_ready;
    sc_signal< sc_lv<32> > call_ret9_stitchNeighbors_fu_352_ap_return_0;
    sc_signal< sc_lv<32> > call_ret9_stitchNeighbors_fu_352_ap_return_1;
    sc_signal< sc_logic > call_ret10_stitchNeighbors_fu_360_ap_ready;
    sc_signal< sc_lv<32> > call_ret10_stitchNeighbors_fu_360_ap_return_0;
    sc_signal< sc_lv<32> > call_ret10_stitchNeighbors_fu_360_ap_return_1;
    sc_signal< sc_logic > call_ret11_stitchNeighbors_fu_368_ap_ready;
    sc_signal< sc_lv<32> > call_ret11_stitchNeighbors_fu_368_ap_return_0;
    sc_signal< sc_lv<32> > call_ret11_stitchNeighbors_fu_368_ap_return_1;
    sc_signal< sc_logic > call_ret12_stitchNeighbors_fu_376_ap_ready;
    sc_signal< sc_lv<32> > call_ret12_stitchNeighbors_fu_376_ap_return_0;
    sc_signal< sc_lv<32> > call_ret12_stitchNeighbors_fu_376_ap_return_1;
    sc_signal< sc_logic > call_ret13_stitchNeighbors_fu_384_ap_ready;
    sc_signal< sc_lv<32> > call_ret13_stitchNeighbors_fu_384_ap_return_0;
    sc_signal< sc_lv<32> > call_ret13_stitchNeighbors_fu_384_ap_return_1;
    sc_signal< sc_logic > call_ret14_stitchNeighbors_fu_392_ap_ready;
    sc_signal< sc_lv<32> > call_ret14_stitchNeighbors_fu_392_ap_return_0;
    sc_signal< sc_lv<32> > call_ret14_stitchNeighbors_fu_392_ap_return_1;
    sc_signal< sc_logic > call_ret15_stitchNeighbors_fu_400_ap_ready;
    sc_signal< sc_lv<32> > call_ret15_stitchNeighbors_fu_400_ap_return_0;
    sc_signal< sc_lv<32> > call_ret15_stitchNeighbors_fu_400_ap_return_1;
    sc_signal< sc_logic > call_ret16_stitchNeighbors_fu_408_ap_ready;
    sc_signal< sc_lv<32> > call_ret16_stitchNeighbors_fu_408_ap_return_0;
    sc_signal< sc_lv<32> > call_ret16_stitchNeighbors_fu_408_ap_return_1;
    sc_signal< sc_logic > call_ret_stitchNeighbors_fu_416_ap_ready;
    sc_signal< sc_lv<32> > call_ret_stitchNeighbors_fu_416_ap_return_0;
    sc_signal< sc_lv<32> > call_ret_stitchNeighbors_fu_416_ap_return_1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_10();
    void thread_ap_return_11();
    void thread_ap_return_12();
    void thread_ap_return_13();
    void thread_ap_return_14();
    void thread_ap_return_15();
    void thread_ap_return_16();
    void thread_ap_return_17();
    void thread_ap_return_18();
    void thread_ap_return_19();
    void thread_ap_return_2();
    void thread_ap_return_20();
    void thread_ap_return_21();
    void thread_ap_return_22();
    void thread_ap_return_23();
    void thread_ap_return_24();
    void thread_ap_return_25();
    void thread_ap_return_26();
    void thread_ap_return_27();
    void thread_ap_return_28();
    void thread_ap_return_29();
    void thread_ap_return_3();
    void thread_ap_return_30();
    void thread_ap_return_31();
    void thread_ap_return_32();
    void thread_ap_return_33();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
};

}

using namespace ap_rtl;

#endif
