// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stitchNeighbors (
        ap_ready,
        Ai_data_V,
        Bi_data_V,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [31:0] Ai_data_V;
input  [31:0] Bi_data_V;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

wire   [2:0] trunc_ln_fu_74_p4;
wire   [2:0] trunc_ln1503_1_fu_90_p4;
wire   [2:0] trunc_ln1503_2_fu_106_p4;
wire   [2:0] trunc_ln1503_3_fu_116_p4;
wire   [9:0] trunc_ln214_fu_132_p1;
wire   [9:0] trunc_ln214_1_fu_146_p1;
wire   [10:0] lhs_V_fu_160_p1;
wire   [10:0] rhs_V_fu_164_p1;
wire   [10:0] ret_V_fu_168_p2;
wire   [8:0] tmp_2_fu_188_p4;
wire   [9:0] trunc_ln1503_4_fu_136_p4;
wire   [31:0] or_ln1356_2_fu_198_p5;
wire   [9:0] add_ln209_fu_222_p2;
wire   [5:0] tmp_5_fu_240_p4;
wire   [9:0] trunc_ln1503_8_fu_150_p4;
wire   [31:0] ret_V_6_fu_250_p6;
wire   [0:0] tmp_fu_180_p3;
wire   [31:0] ret_V_2_fu_216_p2;
wire   [31:0] ret_V_3_fu_228_p5;
wire   [0:0] icmp_ln879_1_fu_100_p2;
wire   [0:0] phiStitch_fu_126_p2;
wire   [0:0] and_ln879_fu_292_p2;
wire   [0:0] icmp_ln879_fu_84_p2;
wire   [0:0] and_ln879_1_fu_298_p2;
wire   [0:0] icmp_ln895_fu_174_p2;
wire   [0:0] and_ln895_fu_304_p2;
wire   [31:0] select_ln895_fu_284_p3;
wire   [31:0] ret_V_1_fu_210_p2;
wire   [0:0] xor_ln895_fu_318_p2;
wire   [0:0] and_ln895_1_fu_324_p2;
wire   [0:0] and_ln895_2_fu_330_p2;
wire   [31:0] select_ln895_1_fu_310_p3;
wire   [31:0] select_ln895_2_fu_336_p3;
wire   [31:0] ret_V_5_fu_270_p6;
wire   [31:0] ret_V_4_fu_264_p2;
wire   [31:0] select_ln895_3_fu_352_p3;
wire   [31:0] select_ln895_4_fu_360_p3;
wire   [31:0] select_ln879_fu_344_p3;
wire   [31:0] select_ln879_1_fu_368_p3;

assign add_ln209_fu_222_p2 = (trunc_ln214_1_fu_146_p1 + trunc_ln214_fu_132_p1);

assign and_ln879_1_fu_298_p2 = (icmp_ln879_fu_84_p2 & and_ln879_fu_292_p2);

assign and_ln879_fu_292_p2 = (phiStitch_fu_126_p2 & icmp_ln879_1_fu_100_p2);

assign and_ln895_1_fu_324_p2 = (xor_ln895_fu_318_p2 & tmp_fu_180_p3);

assign and_ln895_2_fu_330_p2 = (and_ln895_1_fu_324_p2 & and_ln879_1_fu_298_p2);

assign and_ln895_fu_304_p2 = (icmp_ln895_fu_174_p2 & and_ln879_1_fu_298_p2);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln879_fu_344_p3;

assign ap_return_1 = select_ln879_1_fu_368_p3;

assign icmp_ln879_1_fu_100_p2 = ((trunc_ln1503_1_fu_90_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_84_p2 = ((trunc_ln_fu_74_p4 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_174_p2 = ((trunc_ln214_fu_132_p1 > trunc_ln214_1_fu_146_p1) ? 1'b1 : 1'b0);

assign lhs_V_fu_160_p1 = trunc_ln214_fu_132_p1;

assign or_ln1356_2_fu_198_p5 = {{{{tmp_2_fu_188_p4}, {3'd0}}, {trunc_ln1503_4_fu_136_p4}}, {10'd0}};

assign phiStitch_fu_126_p2 = ((trunc_ln1503_2_fu_106_p4 == trunc_ln1503_3_fu_116_p4) ? 1'b1 : 1'b0);

assign ret_V_1_fu_210_p2 = (or_ln1356_2_fu_198_p5 | 32'd4194304);

assign ret_V_2_fu_216_p2 = (or_ln1356_2_fu_198_p5 | 32'd4195327);

assign ret_V_3_fu_228_p5 = {{{{tmp_2_fu_188_p4}, {3'd4}}, {trunc_ln1503_4_fu_136_p4}}, {add_ln209_fu_222_p2}};

assign ret_V_4_fu_264_p2 = (ret_V_6_fu_250_p6 | 32'd1023);

assign ret_V_5_fu_270_p6 = {{{{{tmp_5_fu_240_p4}, {trunc_ln1503_2_fu_106_p4}}, {3'd0}}, {trunc_ln1503_8_fu_150_p4}}, {add_ln209_fu_222_p2}};

assign ret_V_6_fu_250_p6 = {{{{{tmp_5_fu_240_p4}, {trunc_ln1503_2_fu_106_p4}}, {3'd0}}, {trunc_ln1503_8_fu_150_p4}}, {10'd0}};

assign ret_V_fu_168_p2 = (lhs_V_fu_160_p1 + rhs_V_fu_164_p1);

assign rhs_V_fu_164_p1 = trunc_ln214_1_fu_146_p1;

assign select_ln879_1_fu_368_p3 = ((and_ln879_1_fu_298_p2[0:0] === 1'b1) ? select_ln895_4_fu_360_p3 : Bi_data_V);

assign select_ln879_fu_344_p3 = ((and_ln879_1_fu_298_p2[0:0] === 1'b1) ? select_ln895_2_fu_336_p3 : Ai_data_V);

assign select_ln895_1_fu_310_p3 = ((and_ln895_fu_304_p2[0:0] === 1'b1) ? select_ln895_fu_284_p3 : ret_V_1_fu_210_p2);

assign select_ln895_2_fu_336_p3 = ((and_ln895_2_fu_330_p2[0:0] === 1'b1) ? ret_V_1_fu_210_p2 : select_ln895_1_fu_310_p3);

assign select_ln895_3_fu_352_p3 = ((and_ln895_fu_304_p2[0:0] === 1'b1) ? ret_V_6_fu_250_p6 : ret_V_5_fu_270_p6);

assign select_ln895_4_fu_360_p3 = ((and_ln895_2_fu_330_p2[0:0] === 1'b1) ? ret_V_4_fu_264_p2 : select_ln895_3_fu_352_p3);

assign select_ln895_fu_284_p3 = ((tmp_fu_180_p3[0:0] === 1'b1) ? ret_V_2_fu_216_p2 : ret_V_3_fu_228_p5);

assign tmp_2_fu_188_p4 = {{Ai_data_V[31:23]}};

assign tmp_5_fu_240_p4 = {{Bi_data_V[31:26]}};

assign tmp_fu_180_p3 = ret_V_fu_168_p2[32'd10];

assign trunc_ln1503_1_fu_90_p4 = {{Bi_data_V[22:20]}};

assign trunc_ln1503_2_fu_106_p4 = {{Ai_data_V[25:23]}};

assign trunc_ln1503_3_fu_116_p4 = {{Bi_data_V[25:23]}};

assign trunc_ln1503_4_fu_136_p4 = {{Ai_data_V[19:10]}};

assign trunc_ln1503_8_fu_150_p4 = {{Bi_data_V[19:10]}};

assign trunc_ln214_1_fu_146_p1 = Bi_data_V[9:0];

assign trunc_ln214_fu_132_p1 = Ai_data_V[9:0];

assign trunc_ln_fu_74_p4 = {{Ai_data_V[22:20]}};

assign xor_ln895_fu_318_p2 = (icmp_ln895_fu_174_p2 ^ 1'd1);

endmodule //stitchNeighbors
