-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stitchNeighbors is
port (
    ap_ready : OUT STD_LOGIC;
    Ai_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
    Bi_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of stitchNeighbors is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_400000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000010000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal trunc_ln_fu_72_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1503_1_fu_88_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1503_2_fu_104_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1503_3_fu_114_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln214_fu_130_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln214_1_fu_134_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal rhs_V_fu_142_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_V_fu_138_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_fu_146_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_152_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pegged_cEtSum_V_fu_160_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1503_4_fu_180_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal lhs_V_1_fu_190_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_1_fu_194_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_200_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pegged_tEtSum_V_fu_208_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1503_5_fu_222_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_238_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal pegged_tEtSum_V_1_fu_214_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pegged_cEtSum_V_1_fu_166_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_260_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tEt_leftOver_V_fu_232_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lhs_V_2_fu_284_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_4_fu_288_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_294_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pegged_tEtSum_V_2_fu_302_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tEt_leftOver_V_1_fu_316_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp4_fu_322_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal pegged_tEtSum_V_3_fu_308_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln879_1_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phiStitch_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_1_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln895_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_2_fu_248_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln895_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln895_1_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_5_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln895_fu_372_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_3_fu_270_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_6_fu_340_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln895_2_fu_400_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln895_1_fu_392_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln895_3_fu_408_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    and_ln879_1_fu_360_p2 <= (icmp_ln879_fu_82_p2 and and_ln879_fu_354_p2);
    and_ln879_fu_354_p2 <= (phiStitch_fu_124_p2 and icmp_ln879_1_fu_98_p2);
    and_ln895_1_fu_386_p2 <= (xor_ln895_fu_380_p2 and and_ln879_1_fu_360_p2);
    and_ln895_fu_366_p2 <= (icmp_ln895_fu_174_p2 and and_ln879_1_fu_360_p2);
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln895_1_fu_392_p3;
    ap_return_1 <= select_ln895_3_fu_408_p3;
    icmp_ln879_1_fu_98_p2 <= "1" when (trunc_ln1503_1_fu_88_p4 = ap_const_lv3_0) else "0";
    icmp_ln879_fu_82_p2 <= "1" when (trunc_ln_fu_72_p4 = ap_const_lv3_4) else "0";
    icmp_ln895_fu_174_p2 <= "1" when (unsigned(trunc_ln214_fu_130_p1) > unsigned(trunc_ln214_1_fu_134_p1)) else "0";
    lhs_V_1_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1503_4_fu_180_p4),11));
    lhs_V_2_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1503_5_fu_222_p4),11));
    lhs_V_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln214_fu_130_p1),11));
    pegged_cEtSum_V_1_fu_166_p3 <= 
        ap_const_lv10_3FF when (tmp_2_fu_152_p3(0) = '1') else 
        pegged_cEtSum_V_fu_160_p2;
    pegged_cEtSum_V_fu_160_p2 <= std_logic_vector(unsigned(trunc_ln214_fu_130_p1) + unsigned(trunc_ln214_1_fu_134_p1));
    pegged_tEtSum_V_1_fu_214_p3 <= 
        ap_const_lv10_3FF when (tmp_3_fu_200_p3(0) = '1') else 
        pegged_tEtSum_V_fu_208_p2;
    pegged_tEtSum_V_2_fu_302_p2 <= std_logic_vector(unsigned(trunc_ln214_fu_130_p1) + unsigned(trunc_ln1503_5_fu_222_p4));
    pegged_tEtSum_V_3_fu_308_p3 <= 
        ap_const_lv10_3FF when (tmp_4_fu_294_p3(0) = '1') else 
        pegged_tEtSum_V_2_fu_302_p2;
    pegged_tEtSum_V_fu_208_p2 <= std_logic_vector(unsigned(trunc_ln214_1_fu_134_p1) + unsigned(trunc_ln1503_4_fu_180_p4));
    phiStitch_fu_124_p2 <= "1" when (trunc_ln1503_2_fu_104_p4 = trunc_ln1503_3_fu_114_p4) else "0";
    ret_V_1_fu_194_p2 <= std_logic_vector(unsigned(lhs_V_1_fu_190_p1) + unsigned(rhs_V_fu_142_p1));
    ret_V_2_fu_248_p5 <= (((tmp_fu_238_p4 & ap_const_lv3_4) & pegged_tEtSum_V_1_fu_214_p3) & pegged_cEtSum_V_1_fu_166_p3);
    ret_V_3_fu_270_p6 <= ((((tmp_1_fu_260_p4 & trunc_ln1503_2_fu_104_p4) & ap_const_lv3_0) & tEt_leftOver_V_fu_232_p2) & ap_const_lv10_0);
    ret_V_4_fu_288_p2 <= std_logic_vector(unsigned(lhs_V_2_fu_284_p1) + unsigned(lhs_V_fu_138_p1));
    ret_V_5_fu_334_p2 <= (tmp4_fu_322_p5 or ap_const_lv32_400000);
    ret_V_6_fu_340_p6 <= ((((tmp_1_fu_260_p4 & trunc_ln1503_2_fu_104_p4) & ap_const_lv3_0) & pegged_tEtSum_V_3_fu_308_p3) & pegged_cEtSum_V_1_fu_166_p3);
    ret_V_fu_146_p2 <= std_logic_vector(unsigned(rhs_V_fu_142_p1) + unsigned(lhs_V_fu_138_p1));
    rhs_V_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln214_1_fu_134_p1),11));
    select_ln895_1_fu_392_p3 <= 
        ret_V_5_fu_334_p2 when (and_ln895_1_fu_386_p2(0) = '1') else 
        select_ln895_fu_372_p3;
    select_ln895_2_fu_400_p3 <= 
        ret_V_3_fu_270_p6 when (and_ln895_fu_366_p2(0) = '1') else 
        Bi_data_V;
    select_ln895_3_fu_408_p3 <= 
        ret_V_6_fu_340_p6 when (and_ln895_1_fu_386_p2(0) = '1') else 
        select_ln895_2_fu_400_p3;
    select_ln895_fu_372_p3 <= 
        ret_V_2_fu_248_p5 when (and_ln895_fu_366_p2(0) = '1') else 
        Ai_data_V;
    tEt_leftOver_V_1_fu_316_p2 <= std_logic_vector(unsigned(trunc_ln1503_4_fu_180_p4) - unsigned(trunc_ln214_fu_130_p1));
    tEt_leftOver_V_fu_232_p2 <= std_logic_vector(unsigned(trunc_ln1503_5_fu_222_p4) - unsigned(trunc_ln214_1_fu_134_p1));
    tmp4_fu_322_p5 <= (((tmp_fu_238_p4 & ap_const_lv3_0) & tEt_leftOver_V_1_fu_316_p2) & ap_const_lv10_0);
    tmp_1_fu_260_p4 <= Bi_data_V(31 downto 26);
    tmp_2_fu_152_p3 <= ret_V_fu_146_p2(10 downto 10);
    tmp_3_fu_200_p3 <= ret_V_1_fu_194_p2(10 downto 10);
    tmp_4_fu_294_p3 <= ret_V_4_fu_288_p2(10 downto 10);
    tmp_fu_238_p4 <= Ai_data_V(31 downto 23);
    trunc_ln1503_1_fu_88_p4 <= Bi_data_V(22 downto 20);
    trunc_ln1503_2_fu_104_p4 <= Ai_data_V(25 downto 23);
    trunc_ln1503_3_fu_114_p4 <= Bi_data_V(25 downto 23);
    trunc_ln1503_4_fu_180_p4 <= Ai_data_V(19 downto 10);
    trunc_ln1503_5_fu_222_p4 <= Bi_data_V(19 downto 10);
    trunc_ln214_1_fu_134_p1 <= Bi_data_V(10 - 1 downto 0);
    trunc_ln214_fu_130_p1 <= Ai_data_V(10 - 1 downto 0);
    trunc_ln_fu_72_p4 <= Ai_data_V(22 downto 20);
    xor_ln895_fu_380_p2 <= (icmp_ln895_fu_174_p2 xor ap_const_lv1_1);
end behav;
