-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stitchInPhi is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of stitchInPhi is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal call_ret1_stitchNeighbors_fu_288_ap_ready : STD_LOGIC;
    signal call_ret1_stitchNeighbors_fu_288_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret1_stitchNeighbors_fu_288_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret2_stitchNeighbors_fu_296_ap_ready : STD_LOGIC;
    signal call_ret2_stitchNeighbors_fu_296_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret2_stitchNeighbors_fu_296_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret3_stitchNeighbors_fu_304_ap_ready : STD_LOGIC;
    signal call_ret3_stitchNeighbors_fu_304_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret3_stitchNeighbors_fu_304_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret4_stitchNeighbors_fu_312_ap_ready : STD_LOGIC;
    signal call_ret4_stitchNeighbors_fu_312_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret4_stitchNeighbors_fu_312_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret5_stitchNeighbors_fu_320_ap_ready : STD_LOGIC;
    signal call_ret5_stitchNeighbors_fu_320_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret5_stitchNeighbors_fu_320_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret6_stitchNeighbors_fu_328_ap_ready : STD_LOGIC;
    signal call_ret6_stitchNeighbors_fu_328_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret6_stitchNeighbors_fu_328_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret7_stitchNeighbors_fu_336_ap_ready : STD_LOGIC;
    signal call_ret7_stitchNeighbors_fu_336_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret7_stitchNeighbors_fu_336_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret8_stitchNeighbors_fu_344_ap_ready : STD_LOGIC;
    signal call_ret8_stitchNeighbors_fu_344_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret8_stitchNeighbors_fu_344_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret9_stitchNeighbors_fu_352_ap_ready : STD_LOGIC;
    signal call_ret9_stitchNeighbors_fu_352_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret9_stitchNeighbors_fu_352_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret10_stitchNeighbors_fu_360_ap_ready : STD_LOGIC;
    signal call_ret10_stitchNeighbors_fu_360_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret10_stitchNeighbors_fu_360_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret11_stitchNeighbors_fu_368_ap_ready : STD_LOGIC;
    signal call_ret11_stitchNeighbors_fu_368_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret11_stitchNeighbors_fu_368_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret12_stitchNeighbors_fu_376_ap_ready : STD_LOGIC;
    signal call_ret12_stitchNeighbors_fu_376_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret12_stitchNeighbors_fu_376_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret13_stitchNeighbors_fu_384_ap_ready : STD_LOGIC;
    signal call_ret13_stitchNeighbors_fu_384_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret13_stitchNeighbors_fu_384_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret14_stitchNeighbors_fu_392_ap_ready : STD_LOGIC;
    signal call_ret14_stitchNeighbors_fu_392_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret14_stitchNeighbors_fu_392_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret15_stitchNeighbors_fu_400_ap_ready : STD_LOGIC;
    signal call_ret15_stitchNeighbors_fu_400_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret15_stitchNeighbors_fu_400_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret16_stitchNeighbors_fu_408_ap_ready : STD_LOGIC;
    signal call_ret16_stitchNeighbors_fu_408_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret16_stitchNeighbors_fu_408_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_stitchNeighbors_fu_416_ap_ready : STD_LOGIC;
    signal call_ret_stitchNeighbors_fu_416_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_stitchNeighbors_fu_416_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);

    component stitchNeighbors IS
    port (
        ap_ready : OUT STD_LOGIC;
        Ai_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
        Bi_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    call_ret1_stitchNeighbors_fu_288 : component stitchNeighbors
    port map (
        ap_ready => call_ret1_stitchNeighbors_fu_288_ap_ready,
        Ai_data_V => p_read,
        Bi_data_V => p_read17,
        ap_return_0 => call_ret1_stitchNeighbors_fu_288_ap_return_0,
        ap_return_1 => call_ret1_stitchNeighbors_fu_288_ap_return_1);

    call_ret2_stitchNeighbors_fu_296 : component stitchNeighbors
    port map (
        ap_ready => call_ret2_stitchNeighbors_fu_296_ap_ready,
        Ai_data_V => p_read1,
        Bi_data_V => p_read18,
        ap_return_0 => call_ret2_stitchNeighbors_fu_296_ap_return_0,
        ap_return_1 => call_ret2_stitchNeighbors_fu_296_ap_return_1);

    call_ret3_stitchNeighbors_fu_304 : component stitchNeighbors
    port map (
        ap_ready => call_ret3_stitchNeighbors_fu_304_ap_ready,
        Ai_data_V => p_read2,
        Bi_data_V => p_read19,
        ap_return_0 => call_ret3_stitchNeighbors_fu_304_ap_return_0,
        ap_return_1 => call_ret3_stitchNeighbors_fu_304_ap_return_1);

    call_ret4_stitchNeighbors_fu_312 : component stitchNeighbors
    port map (
        ap_ready => call_ret4_stitchNeighbors_fu_312_ap_ready,
        Ai_data_V => p_read3,
        Bi_data_V => p_read20,
        ap_return_0 => call_ret4_stitchNeighbors_fu_312_ap_return_0,
        ap_return_1 => call_ret4_stitchNeighbors_fu_312_ap_return_1);

    call_ret5_stitchNeighbors_fu_320 : component stitchNeighbors
    port map (
        ap_ready => call_ret5_stitchNeighbors_fu_320_ap_ready,
        Ai_data_V => p_read4,
        Bi_data_V => p_read21,
        ap_return_0 => call_ret5_stitchNeighbors_fu_320_ap_return_0,
        ap_return_1 => call_ret5_stitchNeighbors_fu_320_ap_return_1);

    call_ret6_stitchNeighbors_fu_328 : component stitchNeighbors
    port map (
        ap_ready => call_ret6_stitchNeighbors_fu_328_ap_ready,
        Ai_data_V => p_read5,
        Bi_data_V => p_read22,
        ap_return_0 => call_ret6_stitchNeighbors_fu_328_ap_return_0,
        ap_return_1 => call_ret6_stitchNeighbors_fu_328_ap_return_1);

    call_ret7_stitchNeighbors_fu_336 : component stitchNeighbors
    port map (
        ap_ready => call_ret7_stitchNeighbors_fu_336_ap_ready,
        Ai_data_V => p_read6,
        Bi_data_V => p_read23,
        ap_return_0 => call_ret7_stitchNeighbors_fu_336_ap_return_0,
        ap_return_1 => call_ret7_stitchNeighbors_fu_336_ap_return_1);

    call_ret8_stitchNeighbors_fu_344 : component stitchNeighbors
    port map (
        ap_ready => call_ret8_stitchNeighbors_fu_344_ap_ready,
        Ai_data_V => p_read7,
        Bi_data_V => p_read24,
        ap_return_0 => call_ret8_stitchNeighbors_fu_344_ap_return_0,
        ap_return_1 => call_ret8_stitchNeighbors_fu_344_ap_return_1);

    call_ret9_stitchNeighbors_fu_352 : component stitchNeighbors
    port map (
        ap_ready => call_ret9_stitchNeighbors_fu_352_ap_ready,
        Ai_data_V => p_read8,
        Bi_data_V => p_read25,
        ap_return_0 => call_ret9_stitchNeighbors_fu_352_ap_return_0,
        ap_return_1 => call_ret9_stitchNeighbors_fu_352_ap_return_1);

    call_ret10_stitchNeighbors_fu_360 : component stitchNeighbors
    port map (
        ap_ready => call_ret10_stitchNeighbors_fu_360_ap_ready,
        Ai_data_V => p_read9,
        Bi_data_V => p_read26,
        ap_return_0 => call_ret10_stitchNeighbors_fu_360_ap_return_0,
        ap_return_1 => call_ret10_stitchNeighbors_fu_360_ap_return_1);

    call_ret11_stitchNeighbors_fu_368 : component stitchNeighbors
    port map (
        ap_ready => call_ret11_stitchNeighbors_fu_368_ap_ready,
        Ai_data_V => p_read10,
        Bi_data_V => p_read27,
        ap_return_0 => call_ret11_stitchNeighbors_fu_368_ap_return_0,
        ap_return_1 => call_ret11_stitchNeighbors_fu_368_ap_return_1);

    call_ret12_stitchNeighbors_fu_376 : component stitchNeighbors
    port map (
        ap_ready => call_ret12_stitchNeighbors_fu_376_ap_ready,
        Ai_data_V => p_read11,
        Bi_data_V => p_read28,
        ap_return_0 => call_ret12_stitchNeighbors_fu_376_ap_return_0,
        ap_return_1 => call_ret12_stitchNeighbors_fu_376_ap_return_1);

    call_ret13_stitchNeighbors_fu_384 : component stitchNeighbors
    port map (
        ap_ready => call_ret13_stitchNeighbors_fu_384_ap_ready,
        Ai_data_V => p_read12,
        Bi_data_V => p_read29,
        ap_return_0 => call_ret13_stitchNeighbors_fu_384_ap_return_0,
        ap_return_1 => call_ret13_stitchNeighbors_fu_384_ap_return_1);

    call_ret14_stitchNeighbors_fu_392 : component stitchNeighbors
    port map (
        ap_ready => call_ret14_stitchNeighbors_fu_392_ap_ready,
        Ai_data_V => p_read13,
        Bi_data_V => p_read30,
        ap_return_0 => call_ret14_stitchNeighbors_fu_392_ap_return_0,
        ap_return_1 => call_ret14_stitchNeighbors_fu_392_ap_return_1);

    call_ret15_stitchNeighbors_fu_400 : component stitchNeighbors
    port map (
        ap_ready => call_ret15_stitchNeighbors_fu_400_ap_ready,
        Ai_data_V => p_read14,
        Bi_data_V => p_read31,
        ap_return_0 => call_ret15_stitchNeighbors_fu_400_ap_return_0,
        ap_return_1 => call_ret15_stitchNeighbors_fu_400_ap_return_1);

    call_ret16_stitchNeighbors_fu_408 : component stitchNeighbors
    port map (
        ap_ready => call_ret16_stitchNeighbors_fu_408_ap_ready,
        Ai_data_V => p_read15,
        Bi_data_V => p_read32,
        ap_return_0 => call_ret16_stitchNeighbors_fu_408_ap_return_0,
        ap_return_1 => call_ret16_stitchNeighbors_fu_408_ap_return_1);

    call_ret_stitchNeighbors_fu_416 : component stitchNeighbors
    port map (
        ap_ready => call_ret_stitchNeighbors_fu_416_ap_ready,
        Ai_data_V => p_read16,
        Bi_data_V => p_read33,
        ap_return_0 => call_ret_stitchNeighbors_fu_416_ap_return_0,
        ap_return_1 => call_ret_stitchNeighbors_fu_416_ap_return_1);




    ap_ready <= ap_const_logic_1;
    ap_return_0 <= call_ret1_stitchNeighbors_fu_288_ap_return_0;
    ap_return_1 <= call_ret2_stitchNeighbors_fu_296_ap_return_0;
    ap_return_10 <= call_ret11_stitchNeighbors_fu_368_ap_return_0;
    ap_return_11 <= call_ret12_stitchNeighbors_fu_376_ap_return_0;
    ap_return_12 <= call_ret13_stitchNeighbors_fu_384_ap_return_0;
    ap_return_13 <= call_ret14_stitchNeighbors_fu_392_ap_return_0;
    ap_return_14 <= call_ret15_stitchNeighbors_fu_400_ap_return_0;
    ap_return_15 <= call_ret16_stitchNeighbors_fu_408_ap_return_0;
    ap_return_16 <= call_ret_stitchNeighbors_fu_416_ap_return_0;
    ap_return_17 <= call_ret1_stitchNeighbors_fu_288_ap_return_1;
    ap_return_18 <= call_ret2_stitchNeighbors_fu_296_ap_return_1;
    ap_return_19 <= call_ret3_stitchNeighbors_fu_304_ap_return_1;
    ap_return_2 <= call_ret3_stitchNeighbors_fu_304_ap_return_0;
    ap_return_20 <= call_ret4_stitchNeighbors_fu_312_ap_return_1;
    ap_return_21 <= call_ret5_stitchNeighbors_fu_320_ap_return_1;
    ap_return_22 <= call_ret6_stitchNeighbors_fu_328_ap_return_1;
    ap_return_23 <= call_ret7_stitchNeighbors_fu_336_ap_return_1;
    ap_return_24 <= call_ret8_stitchNeighbors_fu_344_ap_return_1;
    ap_return_25 <= call_ret9_stitchNeighbors_fu_352_ap_return_1;
    ap_return_26 <= call_ret10_stitchNeighbors_fu_360_ap_return_1;
    ap_return_27 <= call_ret11_stitchNeighbors_fu_368_ap_return_1;
    ap_return_28 <= call_ret12_stitchNeighbors_fu_376_ap_return_1;
    ap_return_29 <= call_ret13_stitchNeighbors_fu_384_ap_return_1;
    ap_return_3 <= call_ret4_stitchNeighbors_fu_312_ap_return_0;
    ap_return_30 <= call_ret14_stitchNeighbors_fu_392_ap_return_1;
    ap_return_31 <= call_ret15_stitchNeighbors_fu_400_ap_return_1;
    ap_return_32 <= call_ret16_stitchNeighbors_fu_408_ap_return_1;
    ap_return_33 <= call_ret_stitchNeighbors_fu_416_ap_return_1;
    ap_return_4 <= call_ret5_stitchNeighbors_fu_320_ap_return_0;
    ap_return_5 <= call_ret6_stitchNeighbors_fu_328_ap_return_0;
    ap_return_6 <= call_ret7_stitchNeighbors_fu_336_ap_return_0;
    ap_return_7 <= call_ret8_stitchNeighbors_fu_344_ap_return_0;
    ap_return_8 <= call_ret9_stitchNeighbors_fu_352_ap_return_0;
    ap_return_9 <= call_ret10_stitchNeighbors_fu_360_ap_return_0;
end behav;
