// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stitchInPhi (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33
);


output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
input  [31:0] p_read32;
input  [31:0] p_read33;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;
output  [31:0] ap_return_16;
output  [31:0] ap_return_17;
output  [31:0] ap_return_18;
output  [31:0] ap_return_19;
output  [31:0] ap_return_20;
output  [31:0] ap_return_21;
output  [31:0] ap_return_22;
output  [31:0] ap_return_23;
output  [31:0] ap_return_24;
output  [31:0] ap_return_25;
output  [31:0] ap_return_26;
output  [31:0] ap_return_27;
output  [31:0] ap_return_28;
output  [31:0] ap_return_29;
output  [31:0] ap_return_30;
output  [31:0] ap_return_31;
output  [31:0] ap_return_32;
output  [31:0] ap_return_33;

wire    call_ret1_stitchNeighbors_fu_288_ap_ready;
wire   [31:0] call_ret1_stitchNeighbors_fu_288_ap_return_0;
wire   [31:0] call_ret1_stitchNeighbors_fu_288_ap_return_1;
wire    call_ret2_stitchNeighbors_fu_296_ap_ready;
wire   [31:0] call_ret2_stitchNeighbors_fu_296_ap_return_0;
wire   [31:0] call_ret2_stitchNeighbors_fu_296_ap_return_1;
wire    call_ret3_stitchNeighbors_fu_304_ap_ready;
wire   [31:0] call_ret3_stitchNeighbors_fu_304_ap_return_0;
wire   [31:0] call_ret3_stitchNeighbors_fu_304_ap_return_1;
wire    call_ret4_stitchNeighbors_fu_312_ap_ready;
wire   [31:0] call_ret4_stitchNeighbors_fu_312_ap_return_0;
wire   [31:0] call_ret4_stitchNeighbors_fu_312_ap_return_1;
wire    call_ret5_stitchNeighbors_fu_320_ap_ready;
wire   [31:0] call_ret5_stitchNeighbors_fu_320_ap_return_0;
wire   [31:0] call_ret5_stitchNeighbors_fu_320_ap_return_1;
wire    call_ret6_stitchNeighbors_fu_328_ap_ready;
wire   [31:0] call_ret6_stitchNeighbors_fu_328_ap_return_0;
wire   [31:0] call_ret6_stitchNeighbors_fu_328_ap_return_1;
wire    call_ret7_stitchNeighbors_fu_336_ap_ready;
wire   [31:0] call_ret7_stitchNeighbors_fu_336_ap_return_0;
wire   [31:0] call_ret7_stitchNeighbors_fu_336_ap_return_1;
wire    call_ret8_stitchNeighbors_fu_344_ap_ready;
wire   [31:0] call_ret8_stitchNeighbors_fu_344_ap_return_0;
wire   [31:0] call_ret8_stitchNeighbors_fu_344_ap_return_1;
wire    call_ret9_stitchNeighbors_fu_352_ap_ready;
wire   [31:0] call_ret9_stitchNeighbors_fu_352_ap_return_0;
wire   [31:0] call_ret9_stitchNeighbors_fu_352_ap_return_1;
wire    call_ret10_stitchNeighbors_fu_360_ap_ready;
wire   [31:0] call_ret10_stitchNeighbors_fu_360_ap_return_0;
wire   [31:0] call_ret10_stitchNeighbors_fu_360_ap_return_1;
wire    call_ret11_stitchNeighbors_fu_368_ap_ready;
wire   [31:0] call_ret11_stitchNeighbors_fu_368_ap_return_0;
wire   [31:0] call_ret11_stitchNeighbors_fu_368_ap_return_1;
wire    call_ret12_stitchNeighbors_fu_376_ap_ready;
wire   [31:0] call_ret12_stitchNeighbors_fu_376_ap_return_0;
wire   [31:0] call_ret12_stitchNeighbors_fu_376_ap_return_1;
wire    call_ret13_stitchNeighbors_fu_384_ap_ready;
wire   [31:0] call_ret13_stitchNeighbors_fu_384_ap_return_0;
wire   [31:0] call_ret13_stitchNeighbors_fu_384_ap_return_1;
wire    call_ret14_stitchNeighbors_fu_392_ap_ready;
wire   [31:0] call_ret14_stitchNeighbors_fu_392_ap_return_0;
wire   [31:0] call_ret14_stitchNeighbors_fu_392_ap_return_1;
wire    call_ret15_stitchNeighbors_fu_400_ap_ready;
wire   [31:0] call_ret15_stitchNeighbors_fu_400_ap_return_0;
wire   [31:0] call_ret15_stitchNeighbors_fu_400_ap_return_1;
wire    call_ret16_stitchNeighbors_fu_408_ap_ready;
wire   [31:0] call_ret16_stitchNeighbors_fu_408_ap_return_0;
wire   [31:0] call_ret16_stitchNeighbors_fu_408_ap_return_1;
wire    call_ret_stitchNeighbors_fu_416_ap_ready;
wire   [31:0] call_ret_stitchNeighbors_fu_416_ap_return_0;
wire   [31:0] call_ret_stitchNeighbors_fu_416_ap_return_1;

stitchNeighbors call_ret1_stitchNeighbors_fu_288(
    .ap_ready(call_ret1_stitchNeighbors_fu_288_ap_ready),
    .Ai_data_V(p_read),
    .Bi_data_V(p_read17),
    .ap_return_0(call_ret1_stitchNeighbors_fu_288_ap_return_0),
    .ap_return_1(call_ret1_stitchNeighbors_fu_288_ap_return_1)
);

stitchNeighbors call_ret2_stitchNeighbors_fu_296(
    .ap_ready(call_ret2_stitchNeighbors_fu_296_ap_ready),
    .Ai_data_V(p_read1),
    .Bi_data_V(p_read18),
    .ap_return_0(call_ret2_stitchNeighbors_fu_296_ap_return_0),
    .ap_return_1(call_ret2_stitchNeighbors_fu_296_ap_return_1)
);

stitchNeighbors call_ret3_stitchNeighbors_fu_304(
    .ap_ready(call_ret3_stitchNeighbors_fu_304_ap_ready),
    .Ai_data_V(p_read2),
    .Bi_data_V(p_read19),
    .ap_return_0(call_ret3_stitchNeighbors_fu_304_ap_return_0),
    .ap_return_1(call_ret3_stitchNeighbors_fu_304_ap_return_1)
);

stitchNeighbors call_ret4_stitchNeighbors_fu_312(
    .ap_ready(call_ret4_stitchNeighbors_fu_312_ap_ready),
    .Ai_data_V(p_read3),
    .Bi_data_V(p_read20),
    .ap_return_0(call_ret4_stitchNeighbors_fu_312_ap_return_0),
    .ap_return_1(call_ret4_stitchNeighbors_fu_312_ap_return_1)
);

stitchNeighbors call_ret5_stitchNeighbors_fu_320(
    .ap_ready(call_ret5_stitchNeighbors_fu_320_ap_ready),
    .Ai_data_V(p_read4),
    .Bi_data_V(p_read21),
    .ap_return_0(call_ret5_stitchNeighbors_fu_320_ap_return_0),
    .ap_return_1(call_ret5_stitchNeighbors_fu_320_ap_return_1)
);

stitchNeighbors call_ret6_stitchNeighbors_fu_328(
    .ap_ready(call_ret6_stitchNeighbors_fu_328_ap_ready),
    .Ai_data_V(p_read5),
    .Bi_data_V(p_read22),
    .ap_return_0(call_ret6_stitchNeighbors_fu_328_ap_return_0),
    .ap_return_1(call_ret6_stitchNeighbors_fu_328_ap_return_1)
);

stitchNeighbors call_ret7_stitchNeighbors_fu_336(
    .ap_ready(call_ret7_stitchNeighbors_fu_336_ap_ready),
    .Ai_data_V(p_read6),
    .Bi_data_V(p_read23),
    .ap_return_0(call_ret7_stitchNeighbors_fu_336_ap_return_0),
    .ap_return_1(call_ret7_stitchNeighbors_fu_336_ap_return_1)
);

stitchNeighbors call_ret8_stitchNeighbors_fu_344(
    .ap_ready(call_ret8_stitchNeighbors_fu_344_ap_ready),
    .Ai_data_V(p_read7),
    .Bi_data_V(p_read24),
    .ap_return_0(call_ret8_stitchNeighbors_fu_344_ap_return_0),
    .ap_return_1(call_ret8_stitchNeighbors_fu_344_ap_return_1)
);

stitchNeighbors call_ret9_stitchNeighbors_fu_352(
    .ap_ready(call_ret9_stitchNeighbors_fu_352_ap_ready),
    .Ai_data_V(p_read8),
    .Bi_data_V(p_read25),
    .ap_return_0(call_ret9_stitchNeighbors_fu_352_ap_return_0),
    .ap_return_1(call_ret9_stitchNeighbors_fu_352_ap_return_1)
);

stitchNeighbors call_ret10_stitchNeighbors_fu_360(
    .ap_ready(call_ret10_stitchNeighbors_fu_360_ap_ready),
    .Ai_data_V(p_read9),
    .Bi_data_V(p_read26),
    .ap_return_0(call_ret10_stitchNeighbors_fu_360_ap_return_0),
    .ap_return_1(call_ret10_stitchNeighbors_fu_360_ap_return_1)
);

stitchNeighbors call_ret11_stitchNeighbors_fu_368(
    .ap_ready(call_ret11_stitchNeighbors_fu_368_ap_ready),
    .Ai_data_V(p_read10),
    .Bi_data_V(p_read27),
    .ap_return_0(call_ret11_stitchNeighbors_fu_368_ap_return_0),
    .ap_return_1(call_ret11_stitchNeighbors_fu_368_ap_return_1)
);

stitchNeighbors call_ret12_stitchNeighbors_fu_376(
    .ap_ready(call_ret12_stitchNeighbors_fu_376_ap_ready),
    .Ai_data_V(p_read11),
    .Bi_data_V(p_read28),
    .ap_return_0(call_ret12_stitchNeighbors_fu_376_ap_return_0),
    .ap_return_1(call_ret12_stitchNeighbors_fu_376_ap_return_1)
);

stitchNeighbors call_ret13_stitchNeighbors_fu_384(
    .ap_ready(call_ret13_stitchNeighbors_fu_384_ap_ready),
    .Ai_data_V(p_read12),
    .Bi_data_V(p_read29),
    .ap_return_0(call_ret13_stitchNeighbors_fu_384_ap_return_0),
    .ap_return_1(call_ret13_stitchNeighbors_fu_384_ap_return_1)
);

stitchNeighbors call_ret14_stitchNeighbors_fu_392(
    .ap_ready(call_ret14_stitchNeighbors_fu_392_ap_ready),
    .Ai_data_V(p_read13),
    .Bi_data_V(p_read30),
    .ap_return_0(call_ret14_stitchNeighbors_fu_392_ap_return_0),
    .ap_return_1(call_ret14_stitchNeighbors_fu_392_ap_return_1)
);

stitchNeighbors call_ret15_stitchNeighbors_fu_400(
    .ap_ready(call_ret15_stitchNeighbors_fu_400_ap_ready),
    .Ai_data_V(p_read14),
    .Bi_data_V(p_read31),
    .ap_return_0(call_ret15_stitchNeighbors_fu_400_ap_return_0),
    .ap_return_1(call_ret15_stitchNeighbors_fu_400_ap_return_1)
);

stitchNeighbors call_ret16_stitchNeighbors_fu_408(
    .ap_ready(call_ret16_stitchNeighbors_fu_408_ap_ready),
    .Ai_data_V(p_read15),
    .Bi_data_V(p_read32),
    .ap_return_0(call_ret16_stitchNeighbors_fu_408_ap_return_0),
    .ap_return_1(call_ret16_stitchNeighbors_fu_408_ap_return_1)
);

stitchNeighbors call_ret_stitchNeighbors_fu_416(
    .ap_ready(call_ret_stitchNeighbors_fu_416_ap_ready),
    .Ai_data_V(p_read16),
    .Bi_data_V(p_read33),
    .ap_return_0(call_ret_stitchNeighbors_fu_416_ap_return_0),
    .ap_return_1(call_ret_stitchNeighbors_fu_416_ap_return_1)
);

assign ap_ready = 1'b1;

assign ap_return_0 = call_ret1_stitchNeighbors_fu_288_ap_return_0;

assign ap_return_1 = call_ret2_stitchNeighbors_fu_296_ap_return_0;

assign ap_return_10 = call_ret11_stitchNeighbors_fu_368_ap_return_0;

assign ap_return_11 = call_ret12_stitchNeighbors_fu_376_ap_return_0;

assign ap_return_12 = call_ret13_stitchNeighbors_fu_384_ap_return_0;

assign ap_return_13 = call_ret14_stitchNeighbors_fu_392_ap_return_0;

assign ap_return_14 = call_ret15_stitchNeighbors_fu_400_ap_return_0;

assign ap_return_15 = call_ret16_stitchNeighbors_fu_408_ap_return_0;

assign ap_return_16 = call_ret_stitchNeighbors_fu_416_ap_return_0;

assign ap_return_17 = call_ret1_stitchNeighbors_fu_288_ap_return_1;

assign ap_return_18 = call_ret2_stitchNeighbors_fu_296_ap_return_1;

assign ap_return_19 = call_ret3_stitchNeighbors_fu_304_ap_return_1;

assign ap_return_2 = call_ret3_stitchNeighbors_fu_304_ap_return_0;

assign ap_return_20 = call_ret4_stitchNeighbors_fu_312_ap_return_1;

assign ap_return_21 = call_ret5_stitchNeighbors_fu_320_ap_return_1;

assign ap_return_22 = call_ret6_stitchNeighbors_fu_328_ap_return_1;

assign ap_return_23 = call_ret7_stitchNeighbors_fu_336_ap_return_1;

assign ap_return_24 = call_ret8_stitchNeighbors_fu_344_ap_return_1;

assign ap_return_25 = call_ret9_stitchNeighbors_fu_352_ap_return_1;

assign ap_return_26 = call_ret10_stitchNeighbors_fu_360_ap_return_1;

assign ap_return_27 = call_ret11_stitchNeighbors_fu_368_ap_return_1;

assign ap_return_28 = call_ret12_stitchNeighbors_fu_376_ap_return_1;

assign ap_return_29 = call_ret13_stitchNeighbors_fu_384_ap_return_1;

assign ap_return_3 = call_ret4_stitchNeighbors_fu_312_ap_return_0;

assign ap_return_30 = call_ret14_stitchNeighbors_fu_392_ap_return_1;

assign ap_return_31 = call_ret15_stitchNeighbors_fu_400_ap_return_1;

assign ap_return_32 = call_ret16_stitchNeighbors_fu_408_ap_return_1;

assign ap_return_33 = call_ret_stitchNeighbors_fu_416_ap_return_1;

assign ap_return_4 = call_ret5_stitchNeighbors_fu_320_ap_return_0;

assign ap_return_5 = call_ret6_stitchNeighbors_fu_328_ap_return_0;

assign ap_return_6 = call_ret7_stitchNeighbors_fu_336_ap_return_0;

assign ap_return_7 = call_ret8_stitchNeighbors_fu_344_ap_return_0;

assign ap_return_8 = call_ret9_stitchNeighbors_fu_352_ap_return_0;

assign ap_return_9 = call_ret10_stitchNeighbors_fu_360_ap_return_0;

endmodule //stitchInPhi
